[WIP] Bug 1940057: Build/V1 Informers
openshift/openshift-apiserver pull request #206
Opened 2021-04-29 10:29 UTC by otaviof

2021-04-29 20:19 UTC, gabemontero reviewed
So some suggestions @otaviof  ... think they might help if you are still stuck with your current threads of investigation ... though you might have been on this path already (could not 100% tell from the slack exchange)

in the end I think this might be somewhat analogous to the shared informer mutation stuff I recently had to fix in samples operator,  and the demo I will do tomorrow around using `KUBE_CACHE_MUTATION_DETECTOR` set to "true" as an env on the container in question

2021-04-29 20:19 UTC, gabemontero commented on pkg/build/apiserver/registry/buildlog/rest.go
> +
need to do a 

`buildCopy := build.DeepCopy`

and then use `buildCopy` instead of `build` for the rest of this method

2021-04-29 20:19 UTC, gabemontero commented on pkg/build/apiserver/registry/buildlog/rest.go
> +		previous, err := r.BuildLister.Builds(ns).Get(previousBuildName)
another deep copy of previous after the err check before it is assigned to build and then used later on

2021-04-29 20:19 UTC, gabemontero commented on pkg/build/apiserver/registry/buildlog/rest.go
> +	buildPod, err := r.PodLister.Pods(build.Namespace).Get(buildPodName)
deep copy etc

2021-04-29 20:19 UTC, gabemontero commented on pkg/build/apiserver/registry/buildlog/rest.go
> +			buildPod, err = r.PodLister.Pods(build.Namespace).Get(buildPodName)
deep copy etc.

2021-04-29 20:19 UTC, gabemontero commented on pkg/build/apiserver/registry/buildlog/rest.go
> +				buildPod, err = r.PodLister.Pods(build.Namespace).Get(buildPodName)
deep copy etc.

2021-04-29 20:19 UTC, gabemontero commented on pkg/build/apiserver/registry/buildlog/rest_test.go
>  		fakeWatcher := watch.NewFake()
In conjunction with what @adambkaplan mentioned in slack, and which I think you were on the path for @otaviof if I read the slack exchange correctly, is that I would create a new version for `NewFake()` vs. the default k8s one ... sort of like what was done at https://github.com/openshift/openshift-apiserver/blob/a6220d84588dd916fc13210d3484876832fd37bd/pkg/project/cache/cache.go#L92

then in our "build centric" `fakeWatcher` I would override enough things such that when the client.get is called, you do a DeepCopy like I've mentioned elsewhere in the actual runtime code to avoid cache mutation pain with the SharedInformer stuff in client-go

2021-04-30 12:31 UTC, adambkaplan commented on pkg/build/apiserver/registry/buildlog/rest.go
> +
Is that necessary if the build object is not changed? If we're only using the build object to find its pod, then I don't see why we need to make a copy.

2021-04-30 13:18 UTC, gabemontero commented on pkg/build/apiserver/registry/buildlog/rest.go
> +
technically necessary, no

but best practice, one could say it is "safer"

in particular safer to do it now vs. expecting someone making a change in the future that does do a write to remember to go back and do the deep copy now that he will be changing the object

2021-05-03 10:23 UTC, otaviof commented on pkg/build/apiserver/registry/buildlog/rest.go
> +
Thanks for pointing this out @gabemontero. I have pushed changes to `DeepCopy` objects out of shared cache, so the controller is (thread) safe to interact with them. Please consider.

2021-05-03 11:50 UTC, otaviof commented
/retest

2021-05-04 10:25 UTC, otaviof commented
/retest

2021-05-04 13:53 UTC, gabemontero commented
yeah @otaviof as was discussed in scrum, all the e2e failures look to me as well like the various, well know e2e flakes and perm fail / often fail errors you can find on sippy

I would say you can remove the WIP whenever you are ready.  The PR title probably could be a tad more descriptive.... "switching to build/v1 informers or some such.

I'll take a pass at the code changes in a bit.

2021-05-04 13:53 UTC, gabemontero commented
/retest

2021-05-04 15:02 UTC, gabemontero commented on pkg/build/apiserver/registry/buildlog/rest_test.go
> +	informerFactory := informers.NewSharedInformerFactory(client, 0)
hmm ... are you actually creating real informers for you fake informer?

that could be overkill

did you see this done elsewhere in the apiserver code?

was the fake watcher reference I noted earlier untenable ?

2021-05-05 04:30 UTC, otaviof commented
/retest

2021-05-05 05:03 UTC, otaviof commented on pkg/build/apiserver/registry/buildlog/rest_test.go
> +	informerFactory := informers.NewSharedInformerFactory(client, 0)
I do see other places where we use a fake-client with a regular informer, a couple of examples can be found at [admission_test.go:286](https://github.com/openshift/openshift-apiserver/blob/6a267ebbf4c6d3b3bdacc792c6463ba09f67618f/pkg/image/apiserver/admission/limitrange/admission_test.go#L286-L286) and [imagestreamimport_evaluator_test.go:209](https://github.com/openshift/openshift-apiserver/blob/c8f22885a98f74829c7eb8ea47c2351f77b523a6/pkg/quota/quotaimageexternal/imagestreamtag_evaluator_test.go#L209-L209).

> was the fake watcher reference I noted earlier untenable ?

The previous usage of fake-watcher was causing the racing condition. The informer is based on a watch, and  instantiating a fake-watcher created another. So, we adapted the unit testing to updated the build object directly instead. This subject was [discussed on Slack](https://coreos.slack.com/archives/C014MHHKUSF/p1619692264443400).

2021-05-05 05:20 UTC, otaviof commented on pkg/build/apiserver/registry/buildlog/rest_test.go
>  		fakeWatcher := watch.NewFake()
Thanks for the inputs, both the deep-copy and a replacement approach for teh `fakeWatcher` are in place. For the record :-)

2021-05-05 06:00 UTC, otaviof commented
/retittle Bug 1940057: Pod and Build Informers

2021-05-05 06:01 UTC, otaviof commented
/retitle Bug 1940057: Pod and Build Informers

2021-05-05 12:58 UTC, gabemontero commented on pkg/build/apiserver/registry/buildlog/rest_test.go
> +	informerFactory := informers.NewSharedInformerFactory(client, 0)
yep I was aware of the original cause of the race and that slack thread

I just thought some tweaks to the hint I provided at https://github.com/openshift/openshift-apiserver/pull/206#discussion_r623368805 would be an alternative to using the "real" client to avoid the race

Perhaps the folk in https://github.com/openshift/openshift-apiserver/blob/master/OWNERS will be amenable to using the real client in the unit test, but at first blush that approach seems atypical to me.  If you have not already @otaviof you might want to reach out to them as well in slack.

2021-05-06 05:58 UTC, otaviof commented
/retest

2021-05-06 06:30 UTC, otaviof commented on pkg/build/apiserver/registry/buildlog/rest_test.go
> +	informerFactory := informers.NewSharedInformerFactory(client, 0)
> I just thought some tweaks to the hint I provided at [#206 (comment)](https://github.com/openshift/openshift-apiserver/pull/206#discussion_r623368805) would be an alternative to using the "real" client to avoid the race

The hints were useful, having a deep-copy in this condition is recommended. However, I need to highlight we have a *fake-client*, with a regular informer. Also, the root of the race-condition is having two watches competing with each other.

2021-05-06 08:52 UTC, otaviof commented
/test e2e-aws-builds
/test e2e-aws-upgrade

2021-05-06 09:08 UTC, xiuwang commented
I launched a cluster from this pr, then triggered hundreds of builds. There are no lot of list build messages in the apiserver pod.

2021-05-06 13:47 UTC, gabemontero commented on pkg/build/apiserver/registry/buildlog/rest_test.go
> +	informerFactory := informers.NewSharedInformerFactory(client, 0)
@otaviof and I talked during scrum.  Let's leave this as is, and see if the apiserver team is good with this and I'm just being too nervous :-)

2021-05-06 13:48 UTC, gabemontero commented on pkg/build/apiserver/registry/buildlog/rest_test.go
> +	informerFactory := informers.NewSharedInformerFactory(client, 0)
and I missed the prior examples @otaviof cited ... so yeah we are good here

2021-05-06 13:51 UTC, otaviof commented
/test e2e-aws-builds
/test e2e-aws-upgrade

2021-05-06 14:01 UTC, otaviof commented
/retest

2021-05-07 05:00 UTC, otaviof commented
/assign @sttts

Would you please consider this pull-request? Thanks in advance.

2021-05-08 08:31 UTC, xiuwang commented
@otaviof I triggered multiple builds and disconnect apiserver on the cluster launched from pr, then the metric `sum(increase(apiserver_request_total{resource="pods"}[1m])) by (namespace,resource)` only shows default namespace requests, if that's accepted?

http://pastebin.test.redhat.com/962253
![image](https://user-images.githubusercontent.com/5475035/117532374-d50cf800-b019-11eb-8b59-4e997d5d10e5.png)

2021-05-10 08:39 UTC, otaviof commented
> @otaviof I triggered multiple builds and disconnect apiserver on the cluster launched from pr, then the metric `sum(increase(apiserver_request_total{resource="pods"}[1m])) by (namespace,resource)` only shows default namespace requests, if that's accepted?
> 
> http://pastebin.test.redhat.com/962253
> ![image](https://user-images.githubusercontent.com/5475035/117532374-d50cf800-b019-11eb-8b59-4e997d5d10e5.png)

Thanks for checking this @xiuwang! I tried to reproduce the scenario of running 100 builds, and checking the amount of `LIST` requests. The first image is on a cluster with this pull-request:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/11710/117630675-b9216780-b17b-11eb-8eeb-d394f59d0d9a.png">

And, here we have a latest OpenShift 4.7 to compare:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/11710/117630789-d5bd9f80-b17b-11eb-8d4d-638a946ce9e9.png">

So, I think this behavior is expected. We can observe less pressure on the cluster apiserver.

2021-05-10 09:43 UTC, xiuwang commented
@otaviof  Thanks for the comparing.
According above result, the openshift-apiserver doesn't increase pressure when a hundred builds are running.

/label qe-approved

2021-05-11 11:52 UTC, adambkaplan reviewed
A few questions/nits on the unit tests, main logic looks good.

2021-05-11 11:52 UTC, adambkaplan commented on pkg/build/apiserver/registry/buildlog/rest_test.go
> +	podInformer := fakeCoreV1PodInformer(client, informersCtx.Done())
Assuming using the provided context:
```suggestion
	podInformer := fakeCoreV1PodInformer(client, ctx.Done())
```

2021-05-11 11:52 UTC, adambkaplan commented on pkg/build/apiserver/registry/buildlog/rest_test.go
> +	buildInformer := fakeBuildV1Informer(buildClient, informersCtx.Done())
Assuming using the provided context:
```suggestion
	buildInformer := fakeBuildV1Informer(buildClient, ctx.Done())
```

2021-05-11 11:52 UTC, adambkaplan commented on pkg/build/apiserver/registry/buildlog/rest_test.go
> +		informersCtx.Done(),
Assuming using provided context:
```suggestion
		ctx.Done(),
```

2021-05-12 07:21 UTC, otaviof commented on pkg/build/apiserver/registry/buildlog/rest_test.go
> +	defer cancel()
Sure! Those are two different types of context with two different objectives. The original instance is used by the rest-storage to [extract the Kubernetes namespace](https://github.com/openshift/openshift-apiserver/blob/4e3c36dcdf9d8e76998320aba5894b3bb8d16492/pkg/build/apiserver/registry/buildlog/rest.go#L82). And, the `context.WithCancel` was introduced to mitigate the racing-conditions we faced early on, making possible to `cancel()` at the end of each test interaction.

2021-05-12 07:23 UTC, otaviof commented on pkg/build/apiserver/registry/buildlog/rest_test.go
> +	podInformer := fakeCoreV1PodInformer(client, informersCtx.Done())
Please consider [this comment](https://github.com/openshift/openshift-apiserver/pull/206#discussion_r630787588).

2021-05-12 07:23 UTC, otaviof commented on pkg/build/apiserver/registry/buildlog/rest_test.go
> +	buildInformer := fakeBuildV1Informer(buildClient, informersCtx.Done())
Please consider [this comment](https://github.com/openshift/openshift-apiserver/pull/206#discussion_r630787588).

2021-05-12 07:23 UTC, otaviof commented on pkg/build/apiserver/registry/buildlog/rest_test.go
> +		informersCtx.Done(),
Please consider [this comment](https://github.com/openshift/openshift-apiserver/pull/206#discussion_r630787588).

2021-05-12 08:12 UTC, otaviof commented on pkg/build/apiserver/registry/buildlog/rest_test.go
>  	for _, tt := range tests {
Indeed, thanks for the suggestion. Please consider latest changes.

2021-05-12 08:13 UTC, otaviof commented on pkg/build/apiserver/registry/buildlog/rest_test.go
> +		cancel()
Please consider latest changes.

2021-05-12 08:22 UTC, otaviof commented
/test unit

2021-05-12 10:18 UTC, otaviof commented
/test e2e-cmd

2021-05-12 12:02 UTC, otaviof commented
/test e2e-aws-upgrade

2021-05-12 12:25 UTC, adambkaplan approved these changes
/lgtm

2021-05-12 12:25 UTC, adambkaplan commented on pkg/build/apiserver/registry/buildlog/rest_test.go
> +	defer cancel()
makes sense

2021-05-12 12:26 UTC, adambkaplan commented
/assign @deads2k

2021-05-13 03:23 UTC, otaviof commented
/test e2e-aws-upgrade

2021-05-18 13:39 UTC, deads2k commented on pkg/cmd/openshift-apiserver/openshiftapiserver/informers.go
> +	buildClient, err := buildclient.NewForConfig(kubeClientConfig)
this should be a loopback connection.  kubeclients go to kube-apiserver and back.  You can go directly back to localhost.

2021-05-18 14:07 UTC, adambkaplan requested changes

2021-05-18 14:07 UTC, adambkaplan commented on pkg/cmd/openshift-apiserver/openshiftapiserver/informers.go
> +	buildClient, err := buildclient.NewForConfig(kubeClientConfig)
@otaviof like this:

```suggestion
	buildClient, err := buildclient.NewForConfig(loopbackClientConfig)
```

2021-05-18 14:46 UTC, adambkaplan commented
@otaviof squash the last two commits and I'll re-tag lgtm.

2021-05-18 15:13 UTC, otaviof commented
> @otaviof squash the last two commits and I'll re-tag lgtm.

Thanks for the patch (loopback client), and just pushed the squashed commits.

2021-05-19 03:51 UTC, otaviof commented
/test e2e-aws-serial

2021-05-19 17:42 UTC, adambkaplan requested changes
@otaviof code nits at this point, otherwise looks good.

2021-05-19 17:42 UTC, adambkaplan commented on pkg/build/apiserver/apiserver.go
> +	kubeinformers "k8s.io/client-go/informers"
@otaviof nit - this should be with the other k8s.io imports

2021-05-19 17:42 UTC, adambkaplan commented on pkg/build/apiserver/registry/buildlog/rest.go
> +	corev1listers "k8s.io/client-go/listers/core/v1"
nit - should be with the other k8s.io imports

2021-05-19 17:42 UTC, adambkaplan commented on pkg/build/apiserver/registry/wait/rest.go
> +) (*buildv1.Build, bool, error) {
It doesn't look like this function did not change its signature, better off leaving it as is.

2021-05-19 17:42 UTC, adambkaplan commented on pkg/build/apiserver/registry/buildlog/rest_test.go
> +	"k8s.io/client-go/tools/cache"
nit - no line break here so that k8s.io imports are grouped together. `go fmt` will sort them alphabetically.

```suggestion
	"k8s.io/client-go/tools/cache"
```

2021-05-19 17:44 UTC, adambkaplan commented
/retitle Bug 1940057: Use listers to find pod info for build logs

2021-05-20 04:45 UTC, otaviof commented on pkg/build/apiserver/apiserver.go
> +	kubeinformers "k8s.io/client-go/informers"
Done, please consider latest commit. Thanks!

2021-05-20 04:45 UTC, otaviof commented on pkg/build/apiserver/registry/wait/rest.go
> +) (*buildv1.Build, bool, error) {
Indeed, moving it back to original.

2021-05-21 06:08 UTC, otaviof commented
/test e2e-cmd
/test e2e-aws-serial
/test e2e-aws-builds

2021-05-21 14:20 UTC, adambkaplan approved these changes
/lgtm

2021-05-24 09:33 UTC, xiuwang commented
Launch cluster from pr, then trigger hundreds of builds, check pod LIST request. There is less pressure on cluster apiserver.
![image](https://user-images.githubusercontent.com/5475035/119327863-04786180-bcb6-11eb-9e5a-e1a530fcae3e.png)

2021-05-25 07:09 UTC, sttts commented on pkg/build/apiserver/registry/buildlog/rest.go
> +				buildPod = buildPod.DeepCopy()
Why deep copy? Is it mutated? Where?

2021-05-25 07:10 UTC, sttts commented on pkg/build/apiserver/registry/buildlog/rest.go
> +			buildPod = buildPod.DeepCopy()
is it mutated?

2021-05-25 07:10 UTC, sttts commented on pkg/build/apiserver/registry/buildlog/rest.go
> +			buildPod = buildPod.DeepCopy()
same for all the other deepcopies.

2021-05-25 07:12 UTC, sttts commented on pkg/build/apiserver/registry/buildlog/rest.go
> +	build, err := r.BuildLister.Builds(ns).Get(name)
I can see why we use an informer for pods. I don't see why for builds too.

2021-05-25 12:18 UTC, otaviof commented on pkg/build/apiserver/registry/buildlog/rest.go
> +				buildPod = buildPod.DeepCopy()
And indeed, I also don't see where it mutates, so let me revert those bits and test.

2021-05-25 12:29 UTC, otaviof commented on pkg/build/apiserver/registry/buildlog/rest.go
> +	build, err := r.BuildLister.Builds(ns).Get(name)
Would it have side effects to have an informer for builds? The reasoning was based on the BZ main theme, reducing the amount of direct apisever requests.

2021-05-26 03:19 UTC, otaviof commented
/test e2e-cmd
/test e2e-aws
/test e2e-aws-builds

2021-05-26 05:53 UTC, otaviof commented
/retest

2021-05-26 10:45 UTC, otaviof commented
/retest

2021-05-26 14:53 UTC, adambkaplan requested changes
Looks like a few things were missed when the build informers were ripped out.

2021-05-26 14:53 UTC, adambkaplan commented on pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go
> +	BuildInformers buildinformer.SharedInformerFactory
We don't need build informers any more

2021-05-26 14:53 UTC, adambkaplan commented on pkg/cmd/openshift-apiserver/openshiftapiserver/config.go
> +			BuildInformers:                     informers.buildInformers,
Don't need this any more

2021-05-26 14:53 UTC, adambkaplan commented on pkg/cmd/openshift-apiserver/openshiftapiserver/informers.go
> +	}
Not needed any more

2021-05-26 14:53 UTC, adambkaplan commented on pkg/cmd/openshift-apiserver/openshiftapiserver/informers.go
> +		buildInformers:         buildinformer.NewSharedInformerFactory(buildClient, defaultInformerResyncPeriod),
Not needed any more

2021-05-26 14:53 UTC, adambkaplan commented on pkg/cmd/openshift-apiserver/openshiftapiserver/informers.go
> +	i.buildInformers.Start(stopCh)
Not needed any more

2021-05-26 14:53 UTC, adambkaplan commented on pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go
> +	}
Not needed - can be removed

2021-05-26 14:53 UTC, adambkaplan commented on pkg/build/apiserver/registry/buildlog/rest.go
> +		Timeout:   defaultTimeout,
Missed setting the BuildClient here - this is probably why all build tests are bombing out.

```suggestion
		BuildClient: buildClient,
		PodClient:   podClient,
		PodLister:   podLister,
		Timeout:     defaultTimeout,
```

2021-05-26 19:43 UTC, adambkaplan commented
/retest

infra flake installing the cluster

2021-05-27 10:19 UTC, otaviof commented
/retest

2021-05-27 16:41 UTC, otaviof commented
/retest

2021-05-27 17:50 UTC, adambkaplan requested changes
Still have a few dangling references to BuildInformers

2021-05-27 17:50 UTC, adambkaplan commented on pkg/cmd/openshift-apiserver/openshiftapiserver/informers.go
> +	buildInformers         buildinformer.SharedInformerFactory
buildInformers is still here - not needed

2021-05-27 17:50 UTC, adambkaplan commented on pkg/cmd/openshift-apiserver/openshiftapiserver/informers.go
> +	i.buildInformers.Start(stopCh)
Still here - needs to be removed

2021-05-27 17:54 UTC, otaviof commented on pkg/cmd/openshift-apiserver/openshiftapiserver/informers.go
> +	buildInformers         buildinformer.SharedInformerFactory
Thanks!

2021-05-28 03:23 UTC, otaviof commented
/retest

2021-05-31 03:53 UTC, otaviof commented
/retest

2021-06-02 00:37 UTC, adambkaplan approved these changes
/lgtm

2021-06-03 18:05 UTC, adambkaplan commented
/assign @deads2k @sttts @mfojtik

2021-06-06 23:09 UTC, cuppett commented
@deads2k @sttts @mfojtik can we get a review/approval here before code freeze this week?

2021-06-07 07:02 UTC, sttts commented on pkg/build/apiserver/apiserver.go
> +	KubeInformers kubeinformers.SharedInformerFactory
RecommendedConfig has this already

2021-06-07 07:03 UTC, sttts commented
Please use RecommendedConfig's informers. Otherwise sgtm.

2021-06-07 07:33 UTC, otaviof commented on pkg/build/apiserver/apiserver.go
> +	KubeInformers kubeinformers.SharedInformerFactory
Thanks! Removed this entry and using from existing instance. Please consider last push.

2021-06-07 10:19 UTC, otaviof commented
/retest

2021-06-07 13:22 UTC, otaviof commented
/retest

2021-06-07 14:49 UTC, otaviof commented
/retest

2021-06-07 15:30 UTC, adambkaplan approved these changes
/lgtm

2021-06-07 17:32 UTC, sttts commented
/approve

2021-06-08 03:55 UTC, otaviof commented
/retest

2021-06-08 06:35 UTC, otaviof commented
/retest

2021-06-08 14:35 UTC, otaviof commented
/retest

2021-06-08 19:23 UTC, adambkaplan commented
/retest

2021-06-09 05:55 UTC, otaviof commented
/retest

2021-06-09 11:55 UTC, cuppett commented
/retest

2021-06-09 13:16 UTC, bparees commented
/override ci/prow/e2e-aws-upgrade

(this upgrade failure is not related to this pr)

2021-06-09 13:16 UTC, merged