bump(*)
openshift/openshift-apiserver pull request #208
Opened 2021-05-11 16:55 UTC by coreydaley

https://issues.redhat.com/browse/BUILD-87

2021-05-13 19:51 UTC, coreydaley commented
/retest

2021-05-13 19:53 UTC, adambkaplan requested changes

2021-05-13 19:53 UTC, adambkaplan commented on pkg/build/apis/build/v1/zz_generated.conversion.go
> +	// WARNING: in.VolumeMounts requires manual conversion: does not exist in peer-type
@coreydaley You need to add a manual conversion - odd that it is not being auto-generated.

2021-05-13 20:49 UTC, coreydaley commented
/retest

2021-05-14 12:10 UTC, coreydaley commented on pkg/build/apis/build/v1/zz_generated.conversion.go
> +	// WARNING: in.VolumeMounts requires manual conversion: does not exist in peer-type
This should be fixed in the current push

2021-05-14 12:43 UTC, adambkaplan commented on pkg/build/apis/build/types.go
> +	Type BuildVolumeSourceType
One thing I noticed with the build strategy types - they exist in the kube API, but do _not_ exist in the internal representation. We use a conversion function to populate this type discriminator in `conversion.go`.

See https://github.com/openshift/openshift-apiserver/blob/master/pkg/build/apis/build/v1/conversion.go#L137-L154

2021-05-14 14:11 UTC, gabemontero commented
Did you run `make update` @coreydaley and store those changes in a separate commit?  It was hard for me to tell with what you currently have here.

If you have not, you'll need that to get your `ci/prow/verify` runs clean.

2021-05-18 15:38 UTC, adambkaplan commented
/hold

Given the complexity of the feature and the time remaining before 4.8 reaches "final freeze" period, we are going to hold this until master opens for 4.9

2021-05-21 13:18 UTC, coreydaley commented
/retest

2021-05-24 16:54 UTC, coreydaley commented
/retest

2021-05-24 17:39 UTC, adambkaplan requested changes

2021-05-24 17:39 UTC, adambkaplan commented on pkg/build/apis/build/v1/zz_generated.conversion.go
> +	if in.Secret != nil {
@coreydaley I think this is why the generation nit test is failing. Per my prior [comment](https://github.com/openshift/openshift-apiserver/pull/208/files#r632500215), I think what you need is the following:

1. Remove `Type` from the internal representation for BuildVolumeMount
2. Re-run the generated conversions -  this _should_ generate the autoConvert functions
3. Create a separate `Convert_build_BuildVolumeMount_To_v1_BuildVolumeMount` in `conversions.go` which populates the Type field.

2021-05-24 18:52 UTC, coreydaley commented on pkg/build/apis/build/v1/zz_generated.conversion.go
> +	if in.Secret != nil {
So, if I remove the `Type` field, then how would I populate it?
Also, do you mean `BuildVolumeSource`?

2021-05-26 20:14 UTC, coreydaley commented
/retest

2021-05-27 18:10 UTC, coreydaley commented
/retest

2021-05-28 18:05 UTC, coreydaley commented
/retest

2021-06-01 13:54 UTC, coreydaley commented
/retest

2021-06-01 19:18 UTC, adambkaplan commented
@coreydaley looks like the upgrade tests are failing for unrelated reasons. I think it is time to start getting QE to test this new feature, and to write the CI tests that we will add to origin.

@xiuwang for testing this feature, we will want to modify the existing build tests for Secret and ConfigMap build inputs to use the new volumes API. BuildConfig specs will look like this:

```yaml
spec:
  source:
    git: ...
  strategy:
    sourceStrategy:
      ...
      volumes:
        - name: some-secret
          source:
            secret:
              secretName: my-secret
          mounts:
             - destinationPath: /var/run/secret/some-secret
               readOnly: true 
```

PRs needed to test this feature:
- openshift/openshift-apiserver#208
- openshift/openshift-controller-manager#183
- openshift/builder#245

2021-06-01 19:38 UTC, adambkaplan reviewed
/approve

Marking approve to indicate we are ready for QE to begin their verification.

2021-06-02 14:23 UTC, coreydaley commented
/retest

2021-06-02 15:44 UTC, adambkaplan commented
Given the first test by @xiuwang, we need to add validation on the volume name. It needs to

Validations should be added here (using a common method):

1. https://github.com/openshift/openshift-apiserver/blob/master/pkg/build/apis/build/validation/validation.go#L563-L569
2. https://github.com/openshift/openshift-apiserver/blob/master/pkg/build/apis/build/validation/validation.go#L519-L547

Upstream k8s/apimachinery has a method which lets us validate the name is an appropriate DNS label (required by kube for volumes): https://github.com/kubernetes/apimachinery/blob/master/pkg/util/validation/validation.go#L187

2021-06-02 17:02 UTC, coreydaley commented
@adambkaplan Added validation and tests in current push. ptal

2021-06-02 17:12 UTC, coreydaley commented
/retest

2021-06-02 19:03 UTC, coreydaley commented
/retest

2021-06-02 23:24 UTC, coreydaley commented
/retest

2021-06-11 13:26 UTC, xiuwang commented
I have test the feature following test cases https://url.corp.redhat.com/buildvolumes, no critial issue found.

/label qe-approved

2021-06-15 17:11 UTC, coreydaley commented
/retest

2021-06-17 19:11 UTC, adambkaplan commented
@coreydaley based on the error message from @xiuwang in JIRA, perhaps this PR needs to be rebased?

2021-06-21 13:19 UTC, coreydaley commented
/hold cancel

2021-06-21 13:22 UTC, coreydaley commented
@adambkaplan @gabemontero ptal,

2021-06-21 15:28 UTC, coreydaley commented
/retest

2021-06-21 16:37 UTC, coreydaley commented
/retest

2021-06-21 19:29 UTC, coreydaley commented
/retest

2021-06-21 20:12 UTC, coreydaley commented
/retest

2021-06-21 23:32 UTC, coreydaley commented
/retest

2021-06-22 12:35 UTC, coreydaley commented
/retest

2021-06-22 19:50 UTC, gabemontero reviewed
only one question which may be a no-op @coreydaley .... let me know what your think

2021-06-22 19:50 UTC, gabemontero commented on pkg/build/apis/build/validation/validation.go
> +		}
the godoc mentions for the destination path `can not collide with a destination path generated by the builder process`

I'm assuming there is no way for the apiserver to anticipate a path generated down the line by the builder process.  But just in case I'm mentioning it here @coreydaley in case you are aware of perhaps a hard coded path generated by the builder process that the apiserver should check for.

2021-06-22 19:53 UTC, coreydaley commented on pkg/build/apis/build/validation/validation.go
> +		}
This code only validates that everything has been submitted to the apiserver correctly. If there is a collision, the build will have to fail and report it's status. There are some paths that are used, but it would be a nightmare to keep them in sync here.

2021-06-22 20:04 UTC, gabemontero commented on pkg/build/apis/build/validation/validation.go
> +		}
figured it was along those lines ... thanks for confirming @coreydaley

2021-06-22 20:05 UTC, gabemontero commented on pkg/build/apis/build/validation/validation.go
> +		}
I'll add the /lgtm .... if @adambkaplan finds something I did not cite, I'll let him cancel the lgtm

2021-06-22 20:06 UTC, gabemontero commented
I'll add the 

/lgtm

and let @adambkaplan cancel it if he finds something I missed @coredaley

of course you'll need to reach out to apiserver team or maybe @bparees for approve

2021-06-23 15:11 UTC, adambkaplan approved these changes
/lgtm

2021-06-23 15:12 UTC, adambkaplan commented
/retitle BUILD-87: Add Build Volumes API with validation

2021-06-23 15:13 UTC, adambkaplan commented
/assign @sttts @deads2k

2021-06-24 09:53 UTC, sttts commented on hack/openapi-violation.list
> +API rule violation: list_type_missing,github.com/openshift/api/build/v1,BuildVolume,Mounts
can we avoid these?

2021-06-24 09:54 UTC, sttts commented on vendor/github.com/openshift/api/build/v1/types.go
> +	Volumes []BuildVolume `json:"volumes,omitempty" patchStrategy:"merge" patchMergeKey:"name" protobuf:"bytes,9,opt,name=volumes"`
which kind of list is this? You have to declare the liist type.

2021-06-24 09:54 UTC, sttts commented on vendor/github.com/openshift/api/build/v1/types.go
> +	Volumes []BuildVolume `json:"volumes,omitempty" patchStrategy:"merge" patchMergeKey:"name" protobuf:"bytes,9,opt,name=volumes"`
which kind of list is this? You have to declare the liist type.

2021-06-24 09:55 UTC, sttts commented on vendor/github.com/openshift/api/build/v1/types.go
> +	Name string `json:"name" protobuf:"bytes,1,opt,name=name"`
is this required? Needs a tag.

2021-06-24 09:55 UTC, sttts commented on vendor/github.com/openshift/api/build/v1/types.go
> +	Mounts []BuildVolumeMount `json:"mounts" protobuf:"bytes,3,opt,name=mounts"`
Which kind of list is this? Specify list-type.

2021-06-24 09:55 UTC, sttts commented on vendor/github.com/openshift/api/build/v1/types.go
> +	Source BuildVolumeSource `json:"source" protobuf:"bytes,2,opt,name=source"`
is this required?

2021-06-24 09:56 UTC, sttts commented on pkg/build/apis/build/validation/validation.go
> +	if errs := kvalidation.IsDNS1123Label(volume.Name); len(errs) != 0 {
else ...

2021-06-24 09:59 UTC, sttts commented on pkg/build/apis/build/validation/validation.go
> +		allErrs = append(allErrs, field.TooMany(fldPath.Child("source"), len(foundVolumeSources), 1))
I don't think TooMany fits here. Compare:
```
// TooMany returns a *Error indicating "too many". This is used to
// report that a given list has too many items. This is similar to TooLong,
// but the returned error indicates quantity instead of length.
```

This is not a list, but a union.

2021-06-24 09:59 UTC, sttts commented on pkg/build/apis/build/validation/validation.go
> +		allErrs = append(allErrs, field.Invalid(fldPath.Child("source").Child("type"), volume.Source, "source Type and specified type must match"))
lower-case "Type". This is not about the Golang types, but about json.

2021-06-24 10:00 UTC, sttts commented on pkg/build/apis/build/validation/validation.go
> +			allErrs = append(allErrs, field.Required(fldPath.Child("destinationPath"), "must not be blank"))
field path is wrong

2021-06-24 10:01 UTC, sttts commented on pkg/build/apis/build/validation/validation.go
> +	}
would have expected some regex based validation first that defines the string sets positively rather than excluding a few corner cases.

2021-06-24 13:17 UTC, coreydaley commented on vendor/github.com/openshift/api/build/v1/types.go
> +	Name string `json:"name" protobuf:"bytes,1,opt,name=name"`
updated in next push

2021-06-24 15:38 UTC, coreydaley commented on hack/openapi-violation.list
> +API rule violation: list_type_missing,github.com/openshift/api/build/v1,BuildVolume,Mounts
fixed in next push

2021-06-24 15:39 UTC, coreydaley commented on vendor/github.com/openshift/api/build/v1/types.go
> +	Volumes []BuildVolume `json:"volumes,omitempty" patchStrategy:"merge" patchMergeKey:"name" protobuf:"bytes,9,opt,name=volumes"`
addressed via https://github.com/openshift/api/pull/954

2021-06-24 15:39 UTC, coreydaley commented on vendor/github.com/openshift/api/build/v1/types.go
> +	Volumes []BuildVolume `json:"volumes,omitempty" patchStrategy:"merge" patchMergeKey:"name" protobuf:"bytes,9,opt,name=volumes"`
addressed via https://github.com/openshift/api/pull/954

2021-06-24 15:39 UTC, coreydaley commented on vendor/github.com/openshift/api/build/v1/types.go
> +	Name string `json:"name" protobuf:"bytes,1,opt,name=name"`
addressed via https://github.com/openshift/api/pull/954

2021-06-24 15:39 UTC, coreydaley commented on vendor/github.com/openshift/api/build/v1/types.go
> +	Source BuildVolumeSource `json:"source" protobuf:"bytes,2,opt,name=source"`
addressed via https://github.com/openshift/api/pull/954

2021-06-24 15:42 UTC, coreydaley commented on pkg/build/apis/build/validation/validation.go
> +	if errs := kvalidation.IsDNS1123Label(volume.Name); len(errs) != 0 {
Could you elaborate on why this needs an `else` branch?

2021-06-24 15:44 UTC, coreydaley commented on pkg/build/apis/build/validation/validation.go
> +		allErrs = append(allErrs, field.TooMany(fldPath.Child("source"), len(foundVolumeSources), 1))
updated in next push

2021-06-24 15:45 UTC, coreydaley commented on pkg/build/apis/build/validation/validation.go
> +			allErrs = append(allErrs, field.Required(fldPath.Child("destinationPath"), "must not be blank"))
updated in next push

2021-06-24 15:48 UTC, coreydaley commented on pkg/build/apis/build/validation/validation.go
> +	}
This pattern was copied from https://github.com/openshift/openshift-apiserver/blob/master/pkg/build/apis/build/validation/validation.go#L367-L375

2021-06-24 15:49 UTC, coreydaley commented on pkg/build/apis/build/validation/validation.go
> +		allErrs = append(allErrs, field.Invalid(fldPath.Child("source").Child("type"), volume.Source, "source Type and specified type must match"))
updated in next push

2021-06-24 15:49 UTC, coreydaley commented on vendor/github.com/openshift/api/build/v1/types.go
> +	Mounts []BuildVolumeMount `json:"mounts" protobuf:"bytes,3,opt,name=mounts"`
addressed via openshift/api#954

2021-06-24 15:50 UTC, sttts commented on pkg/build/apis/build/validation/validation.go
> +	}
so we say: path can be any utf8 string minus those we check. Does e.g. Windows support matter here?

2021-06-24 15:51 UTC, sttts commented on pkg/build/apis/build/validation/validation.go
> +	if errs := kvalidation.IsDNS1123Label(volume.Name); len(errs) != 0 {
is empty string a DNS1123label? You will get double error now with your code.

2021-06-24 15:52 UTC, coreydaley commented on pkg/build/apis/build/validation/validation.go
> +	if errs := kvalidation.IsDNS1123Label(volume.Name); len(errs) != 0 {
doh! I violated my "always read the next line" rule.
Updated in next push

2021-06-24 15:53 UTC, RickJWagner commented
/label px-approved

2021-06-24 15:54 UTC, RickJWagner commented
PLM agrees.

2021-06-25 14:27 UTC, adambkaplan commented on pkg/build/apis/build/validation/validation.go
> +	}
Windows support does not matter yet. We only support builds for Linux container images today.

2021-06-25 14:28 UTC, adambkaplan commented on pkg/build/apis/build/validation/validation.go
> +	}
(perhaps we need a TODO on that validation if we ever decide to support Windows containers for builds).

2021-06-25 16:22 UTC, coreydaley commented on pkg/build/apis/build/validation/validation.go
> +	}
@sttts Since windows support is not an issue, can this pull request move forward?

2021-06-25 16:42 UTC, sttts commented on pkg/build/apis/build/validation/validation.go
> +	}
yes. Just note that you will never be ableto strengthen the validation here. It will stay as open as it is now.

2021-06-25 17:49 UTC, coreydaley commented on pkg/build/apis/build/validation/validation.go
> +	}
@adambkaplan Are you ok with ^ ?

2021-06-25 19:49 UTC, adambkaplan commented on pkg/build/apis/build/validation/validation.go
> +	}
I think this is fine.

2021-06-25 19:49 UTC, adambkaplan approved these changes
/lgtm

2021-06-25 19:54 UTC, coreydaley commented
@sttts I think we are ready for an approval, the e2e-aws-upgrade test failures are unrelated and being discussed on slack.

2021-06-25 20:20 UTC, sttts commented on pkg/build/apis/build/validation/validation.go
> +	if errs := kvalidation.IsDNS1123Label(volume.Name); len(errs) != 0 {
What I had meant original is still not the case:

```
if len(volume.Name) == 0 {
  allErrs = append(allErrs, field.Required(fldPath.Child("name"), ""))
} else if errs := kvalidation.IsDNS1123Label(volume.Name); len(errs) != 0 {
   ...
}
```

Otherwise you get `["volume.Name is required", "volume.Name is not valid DNS 1123 label"]`.

2021-06-25 20:20 UTC, sttts commented on pkg/build/apis/build/validation/validation.go
> +	} else if len(volume.Source.Type) == 0 {
why this `else`?

2021-06-25 20:21 UTC, sttts commented on pkg/build/apis/build/validation/validation.go
> +		allErrs = append(allErrs, field.Invalid(fldPath.Child("source").Child("type"), volume.Source, "source type and specified type must match"))
`volume.Source` is not the value at the field path.

2021-06-25 20:22 UTC, sttts commented on pkg/build/apis/build/validation/validation.go
> +			allErrs = append(allErrs, field.Invalid(fldPath.Child("name"), volume, e))
volume is not the value at the field path

2021-06-25 20:24 UTC, coreydaley commented on pkg/build/apis/build/validation/validation.go
> +	if errs := kvalidation.IsDNS1123Label(volume.Name); len(errs) != 0 {
updated in current push

2021-06-25 20:24 UTC, sttts commented on pkg/build/apis/build/validation/validation.go
> +		if !filepath.IsAbs(vm.DestinationPath) {
I assume `IsAbs` is false for empty string. You will get two errors now for empty string.

2021-06-25 20:25 UTC, coreydaley commented on pkg/build/apis/build/validation/validation.go
> +			allErrs = append(allErrs, field.Invalid(fldPath.Child("name"), volume, e))
updated in next push

2021-06-25 20:27 UTC, sttts commented
A couple of validation formalities are wrong.

2021-06-25 20:27 UTC, coreydaley commented on pkg/build/apis/build/validation/validation.go
> +		if !filepath.IsAbs(vm.DestinationPath) {
updated in next push

2021-06-25 20:28 UTC, coreydaley commented on pkg/build/apis/build/validation/validation.go
> +		allErrs = append(allErrs, field.Invalid(fldPath.Child("source").Child("type"), volume.Source, "source type and specified type must match"))
updated in next push

2021-06-25 20:29 UTC, coreydaley commented on pkg/build/apis/build/validation/validation.go
> +	} else if len(volume.Source.Type) == 0 {
updated in next push

2021-06-25 20:29 UTC, coreydaley commented
@sttts All comments have been addressed, thanks for the review

2021-06-25 20:41 UTC, sttts commented on pkg/build/apis/build/validation/validation.go
> +				allErrs = append(allErrs, field.Invalid(fldPath.Child("mounts").Index(i).Child("destinationPath"), vm.DestinationPath, "destination path must not contain ':'"))
cosmetics: all these strings must be written wir the field path as subjects. I.e. here: `must not contain ":"`. Otherwise you will get `mounts.destinationPath "bla:bla" destination path must not contain ':' `

2021-06-25 20:41 UTC, sttts commented on pkg/build/apis/build/validation/validation.go
> +				allErrs = append(allErrs, field.Invalid(fldPath.Child("mounts").Index(i).Child("destinationPath"), vm.DestinationPath, "destination path must not contain ':'"))
There are some more like that above and below

2021-06-25 20:45 UTC, coreydaley commented on pkg/build/apis/build/validation/validation.go
> +				allErrs = append(allErrs, field.Invalid(fldPath.Child("mounts").Index(i).Child("destinationPath"), vm.DestinationPath, "destination path must not contain ':'"))
updated in current push

2021-06-26 00:56 UTC, coreydaley commented
/retest

2021-06-26 06:29 UTC, sttts commented on pkg/build/apis/build/validation/validation.go
> +		allErrs = append(allErrs, field.Invalid(fldPath.Child("source").Child("type"), volume.Source.Type, "source type and specified type must match"))
this and the one above is still not of shape `must ....`. Follow-up is fine.

2021-06-26 06:30 UTC, sttts commented
/retest
/lgtm
/approve

2021-06-27 17:46 UTC, merged