[WIP] NE-310 HSTS Route Admission Plugin
openshift/openshift-apiserver pull request #224
Opened 2021-06-29 00:48 UTC by candita

Administrators who are tasked with route management and/or regulatory compliance face a number of issues with regard to enforcing HSTS.  For efficiency and protection against configuration errors, they have requested to automatically and globally enable HSTS on the basis of the cluster `Ingress` domains. However, because enabling HSTS automatically and globally can cause disruption of service on a wide scale, they should also be able to audit and change HSTS configuration without further outages.  Finally, they should be able to consistently apply the same HSTS configuration and predict the outcome on any cluster.

- Register a new plugin route.openshift.io/RequiredRouteAnnotations 
- Add a new admissions package called requiredrouteannotations, with methods to validate route annotation configuration
- Add unit tests

Enhancement proposal: https://github.com/openshift/enhancements/pull/749

2021-06-29 13:12 UTC, candita commented
/test verify

2021-06-29 20:32 UTC, candita commented
/test verify

2021-07-14 00:29 UTC, candita commented
/test unit

2021-07-20 02:48 UTC, candita commented
/test verify

2021-07-20 13:52 UTC, candita commented
/retest

2021-07-20 14:36 UTC, sanchezl commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +func NewRequiredRouteAnnotations() (admission.Interface, error) {
```suggestion
func NewRequiredRouteAnnotations() (*requiredRouteAnnotations, error) {
```
It's better to return the concrete type here.

2021-07-20 21:42 UTC, candita commented
/test verify

2021-07-20 22:10 UTC, candita commented
/test verify

2021-07-20 23:12 UTC, candita commented
/test verify

2021-07-21 02:57 UTC, candita commented
/test verify

2021-07-21 23:39 UTC, candita commented
Running step e2e-aws-ipi-install-install.    
{"component":"entrypoint","file":"prow/entrypoint/run.go:169","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Entrypoint received interrupt: terminated","severity":"error","time":"2021-07-21T23:34:21Z"}

/test e2e-aws

2021-07-22 14:29 UTC, candita commented
info: Loading sha256:a4ae2a1ae18b0b4ecf96994e04aa8770d72a611b3cd73460ebb91fde23841910 vsphere-problem-detector
error: unable to parse image registry.build01.ci.openshift.org/ci-op-ml44p4ql/stable-initial@sha256:cceb4cbb8e255ea598f368cd7ed2a09b9b85a5abc86df9dd16a0364837c42662: cannot retrieve image configuration for manifest sha256:cceb4cbb8e255ea598f368cd7ed2a09b9b85a5abc86df9dd16a0364837c42662: received unexpected HTTP status: 500 Internal Server Error

/test e2e-aws-upgrade

2021-07-22 14:46 UTC, Miciah commented on hack/update-generated-openapi.sh
> +    grep --color=never -rl '+k8s:openapi-gen=true' vendor/github.com/openshift/api | \
Were the changes in `hack/update-generated-openapi.sh` required after all?

2021-07-22 15:12 UTC, candita commented on hack/update-generated-openapi.sh
> +    grep --color=never -rl '+k8s:openapi-gen=true' vendor/github.com/openshift/api | \
They are not required by my code, but this could be an issue in the future.  These two files show up as input files and should not, because `+k8s:openapi-gen=false` there:
k8s.io/api/admission/v1
k8s.io/api/admission/v1beta1

2021-07-22 20:15 UTC, candita commented on hack/update-generated-openapi.sh
> +    grep --color=never -rl '+k8s:openapi-gen=true' vendor/github.com/openshift/api | \
If you think it's too risky, I can add to a separate PR

2021-07-22 21:46 UTC, Miciah commented on hack/update-generated-openapi.sh
> +    grep --color=never -rl '+k8s:openapi-gen=true' vendor/github.com/openshift/api | \
I don't object to keeping this, but I cannot speak for other reviewers.

2021-07-22 22:28 UTC, candita commented on hack/update-generated-openapi.sh
> +    grep --color=never -rl '+k8s:openapi-gen=true' vendor/github.com/openshift/api | \
I'll put it in a different PR asap

2021-07-23 21:47 UTC, candita commented
Managed cluster should have same number of Machines and Nodes
Many 137 error codes, will retry
/test e2e-aws

2021-07-23 21:51 UTC, Miciah commented
[e2e-cmd](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_openshift-apiserver/224/pull-ci-openshift-openshift-apiserver-master-e2e-cmd/1418657982308159488) failed on `[sig-cli][Feature:LegacyCommandTests][Disruptive][Serial] test-cmd: test/cmd/basicresources.sh` with the following:

    The Service "frontend" is invalid: spec.clusterIPs: Invalid value: []string{"172.30.182.32"}: failed to allocated ip:172.30.182.32 with error:provided IP is already allocated

/test e2e-cmd

2021-07-24 00:12 UTC, candita commented
/test e2e-aws

2021-07-26 03:37 UTC, sanchezl commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +		match := regexp.MustCompile(fmt.Sprintf("^%s$", matcher))
The documentation for `RequiredHSTSPolicy.DomainPatterns` describes the pattern syntax as a simplified glob-like pattern, not a regex.

2021-07-26 03:37 UTC, sanchezl commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	if a.GetResource().GroupResource() != routev1.Resource("routes") {
```suggestion
	if a.GetResource().GroupResource() != route.Resource("routes") {
```

2021-07-26 03:37 UTC, sanchezl commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	newobject, isRoute := a.GetObject().(*routeapi.Route)
```suggestion
	newObject, isRoute := a.GetObject().(*routeapi.Route)
```

2021-07-26 03:37 UTC, sanchezl commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +func requiredNamespaceDomainMatchesRoute(requirement configv1.RequiredHSTSPolicy, route *routeapi.Route, namespace *corev1.Namespace) (bool, bool, error) {
Consider just returning a single `bool` for a match/no match. You don't seem to have a need to distinguish the values outside this method.

2021-07-26 14:06 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +func NewRequiredRouteAnnotations() (*requiredRouteAnnotations, error) {
This is a `Factory` and requires that unused parameter for the `Plugins.Registry`

2021-07-26 14:15 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +		match := regexp.MustCompile(fmt.Sprintf("^%s$", matcher))
I hadn't intended for that to happen.  I could correct the documentation later, if that's acceptable.

2021-07-26 14:17 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	if a.GetResource().GroupResource() != routev1.Resource("routes") {
Do you want me to change the import alias from `routev1` to `route` here?  And for all the other places I've used the v1 suffix?

2021-07-26 17:36 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +func requiredNamespaceDomainMatchesRoute(requirement configv1.RequiredHSTSPolicy, route *routeapi.Route, namespace *corev1.Namespace) (bool, bool, error) {
done, thanks!

2021-07-26 17:36 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	newobject, isRoute := a.GetObject().(*routeapi.Route)
done, thanks

2021-07-26 17:36 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +		match := regexp.MustCompile(fmt.Sprintf("^%s$", matcher))
Done, thanks!  Thanks @frobware too.

2021-07-26 17:38 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	setExternalKubeInformerFactoryOnce.Do(func() {
I noticed that we don't actually need to call `var _ = initializer.WantsExternalKubeInformerFactory(&requiredRouteAnnotations{})` because it is called automatically.  Removed it and removed the check here.

2021-07-26 17:38 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +var setExternalKubeInformerFactoryOnce sync.Once
no longer needed

2021-07-26 17:39 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	if !o.waitForSyncedStore(ctx) {
done, thanks!

2021-07-26 17:39 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	}
fixed, thanks!

2021-07-26 20:14 UTC, sttts commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	if a.GetResource().GroupResource() != routev1.Resource("routes") {
objects in admission have internal types, not v1.

2021-07-26 20:16 UTC, sttts commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +		if newannotations != nil {
no need for nil check

2021-07-26 20:17 UTC, sttts commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +			klog.Infof("ignoring %v on %s/%s that doesn't change HSTS policy (old=%v, new=%v)", a.GetOperation(), a.GetNamespace(), a.GetName(), oldhsts, newhsts)
request level log output without loglevel is not good. at least make this V(4)

2021-07-26 20:18 UTC, sttts commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	klog.Info("SetExternalKubeInformerFactory was called")
debug code

2021-07-26 20:19 UTC, sttts commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	setExternalKubeInformerFactoryOnce.Do(func() {
the reason for `var _ = type(x)` is not to call anything, but to assert an interface on `x`. If we change the interface, this assertion makes sure we notice that we suddenly don't implement the interface anymore. So please add the assertion again. It's our security net.

2021-07-26 20:21 UTC, sanchezl commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +func NewRequiredRouteAnnotations() (*requiredRouteAnnotations, error) {
This isn't satisfying any interface, just `return NewRequiredRouteAnnotations(), nil` in your actual `Factory` (the function literal inside your call to `plugins.Registry`).

2021-07-26 20:22 UTC, sttts commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	if a.GetResource().GroupResource() != routev1.Resource("routes") {
Actually, I was talking about the group-kind. This is group-resource. Might be that that value is versioned. Wondering whether you really want the resource and not the kind though.

2021-07-26 20:23 UTC, sanchezl commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	if a.GetResource().GroupResource() != routev1.Resource("routes") {
No, just here, use the group level API instead (e.g. import `"github.com/openshift/api/route"`).

2021-07-26 20:25 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +			klog.Infof("ignoring %v on %s/%s that doesn't change HSTS policy (old=%v, new=%v)", a.GetOperation(), a.GetNamespace(), a.GetName(), oldhsts, newhsts)
Will do everywhere.  Thanks.

2021-07-26 20:27 UTC, sttts commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	klog.Infof("allowing %v on %s/%s: %v", a.GetOperation(), a.GetNamespace(), a.GetName(), newRoute)
debug code

2021-07-26 20:29 UTC, sttts commented on pkg/route/apiserver/admission/requiredrouteannotations/admission_test.go
> +*/
debug code

2021-07-26 20:30 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	klog.Info("SetExternalKubeInformerFactory was called")
Sorry. All removed in next push.

2021-07-26 20:37 UTC, sanchezl requested changes

2021-07-26 20:37 UTC, sanchezl commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +		newmetadata, err := meta.Accessor(newObject)
In general, use the expected convention of mixedCaps and initialisms for all the vars in this method. e.g:
`oldhsts` -> `oldHSTS`
`newmetadata` -> `newMetadata`
etc...

2021-07-26 20:37 UTC, sanchezl commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	}
We should keep checking until it _succeeds_ once.
```suggestion
	if !o.syncCachesSynced {
		o.cachesSynced = o.waitForSyncedStore(ctx)
	}
	if !o.syncCachesSynced {
		return admission.NewForbidden(a, errors.New(pluginName+": caches not synchronized: "))
	}
	// all good, continue....
```
Nit: From what I've seen in the logs, we can tell which caches did not sync from the logs output by the informers.

2021-07-26 21:03 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	}
https://github.com/openshift/openshift-apiserver/pull/224/files#diff-cde26a88c8aa9772d3d1cbf96497ac0009504bc258fd662e2ad19b458dcd3d81R37

We are waiting for 10 seconds for it to succeed, but we don't want to wait forever in `Validate`.  Is that acceptable?

2021-07-26 21:19 UTC, candita commented
e2e-aws-upgrade failures coming from
 alert KubeAPIErrorBudgetBurn fired for 210 seconds with labels: {long="6h", severity="critical", short="30m"}

2021-07-26 21:41 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	setExternalKubeInformerFactoryOnce.Do(func() {
ok, thanks.

2021-07-27 01:39 UTC, candita commented
Cluster operator authentication Degraded is True with IngressStateEndpoints_MissingSubsets::OAuthServerConfigObservation_Error::OAuthServerServiceEndpointAccessibleController_SyncError::OAuthServerServiceEndpointsEndpointAccessibleController_SyncError::RouterCerts_NoRouterCertSecret: IngressStateEndpointsDegraded: No subsets found for the endpoints of oauth-server

/test e2e-aws-upgrade

2021-07-27 11:27 UTC, frobware commented
/retitle "Bug 1986148: NE-310 HSTS Route Admission Plugin"

2021-07-27 11:30 UTC, frobware commented
/retitle Bug 1986148: NE-310 HSTS Route Admission Plugin

2021-07-27 11:48 UTC, frobware requested changes
Overall LGTM but we need a test case to cover `SmallestMaxAge`. I did not see this line covered when running `go test` using: 

```bash
$ type cover
cover is a function
cover () 
{ 
    local t="/tmp/go-cover.$$.tmp";
    go test -coverprofile=$t $@ && go tool cover -html=$t
}
```

```go
func (c *hstsConfig) meetsRequirements(requirement configv1.RequiredHSTSPolicy) error {
        ...
        if requirement.MaxAge.SmallestMaxAge != nil && c.maxAge < *requirement.MaxAge.SmallestMaxAge {
                return fmt.Errorf("is less than minimum age (%d)", *requirement.MaxAge.SmallestMaxAge)
        }
```



- We need to follow up with end to end testing.

- I also would like to understand what happens on upgrade where the cluster has, say, 10,000 routes. From what I can see `Validate()` will back off until the caches have sync'd, but what will continue to call `Validate()` for all the existing routes where we return early (because we are not sync'd)?

2021-07-27 11:48 UTC, frobware commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +			synced = append(synced, fmt.Sprintf("%s", n))
We don't need this loop; instead this can be:

```go
	if !o.cachesSynced {
		return admission.NewForbidden(a, errors.New(pluginName+": caches not synchronized: "+strings.Join(o.cachesToSyncNames, ", ")))
	}
```

2021-07-27 11:48 UTC, frobware commented on pkg/route/apiserver/admission/requiredrouteannotations/admission_test.go
> +		indexer.Add(fakeNamespace(namespace, labels))
It may be benign but we should just that `Add()` was successful. Consider adding: 

```diff
From d4658691a41d4cb72b3e7dd99dcc1d70875e2d9e Mon Sep 17 00:00:00 2001
From: Andrew McDermott <amcdermo@redhat.com>
Date: Tue, 27 Jul 2021 10:17:40 +0100
Subject: [PATCH] Check for Index.Add() failures

---
 .../requiredrouteannotations/admission_test.go       | 12 +++++++++---
 1 file changed, 9 insertions(+), 3 deletions(-)

diff --git a/pkg/route/apiserver/admission/requiredrouteannotations/admission_test.go b/pkg/route/apiserver/admission/requiredrouteannotations/admission_test.go
index 690012d1e..1922e954f 100644
--- a/pkg/route/apiserver/admission/requiredrouteannotations/admission_test.go
+++ b/pkg/route/apiserver/admission/requiredrouteannotations/admission_test.go
@@ -473,14 +473,18 @@ func fakeIngress(name string, config configv1.Ingress) *configv1.Ingress {
 func fakeNamespaceLister(namespacesAndLabels map[string]map[string]string) corev1listers.NamespaceLister {
 	indexer := cache.NewIndexer(cache.MetaNamespaceKeyFunc, cache.Indexers{})
 	for namespace, labels := range namespacesAndLabels {
-		indexer.Add(fakeNamespace(namespace, labels))
+		if err := indexer.Add(fakeNamespace(namespace, labels)); err != nil {
+			panic(err.Error())
+		}
 	}
 	return corev1listers.NewNamespaceLister(indexer)
 }
 
 func fakeIngressLister(name string, config configv1.Ingress) configv1listers.IngressLister {
 	indexer := cache.NewIndexer(cache.MetaNamespaceKeyFunc, cache.Indexers{})
-	indexer.Add(fakeIngress(name, config))
+	if err := indexer.Add(fakeIngress(name, config)); err != nil {
+		panic(err.Error())
+	}
 	return configv1listers.NewIngressLister(indexer)
 }
 
@@ -488,7 +492,9 @@ func fakeRouteLister(routeDetails map[string]map[string]string, spec *routeapi.R
 	indexer := cache.NewIndexer(cache.MetaNamespaceKeyFunc, cache.Indexers{})
 	for rt, namespaceAndLabels := range routeDetails {
 		for ns := range namespaceAndLabels {
-			indexer.Add(fakeRoute(rt, ns, spec, namespaceAndLabels))
+			if err := indexer.Add(fakeRoute(rt, ns, spec, namespaceAndLabels)); err != nil {
+				panic(err.Error())
+			}
 		}
 	}
 	return routev1listers.NewRouteLister(indexer)
-- 
2.31.1
```

2021-07-27 13:34 UTC, candita commented
/bugzilla refresh

2021-07-27 14:03 UTC, frobware commented
/bugzilla refresh

2021-07-27 14:17 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission_test.go
> +		indexer.Add(fakeNamespace(namespace, labels))
Done, thanks.

2021-07-27 14:17 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +			synced = append(synced, fmt.Sprintf("%s", n))
I've just taken care of these, thanks for the feedback.

Validate will block for up to 10 seconds the first time it is called to get caches sync'd.  It only needs to do that once.  In my manual testing, it logs less than 1/10th of a second to do that the first time (with only default routes).  I will do some further testing to provide an answer on upgrade with 10,000 routes.  I was (perhaps naively) relying on the admission framework to take care of this as a separation of concerns.

2021-07-27 14:24 UTC, frobware commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +			synced = append(synced, fmt.Sprintf("%s", n))
> Validate will block for up to 10 seconds the first time it is called to get caches sync'd.

Where is this 10 second specified? As part of the way sync works internally/

2021-07-27 15:42 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	}
Spoke with @frobware and I understand now.  Will post a change.

2021-07-27 15:42 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +			synced = append(synced, fmt.Sprintf("%s", n))
As discussed, will change to 30 seconds.

2021-07-27 16:44 UTC, frobware commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	namespace, err := o.nsLister.Get(newRoute.Namespace)
Isn't this redundant? Will `namespace` be different to `newRouter.Namespace`?

2021-07-27 16:45 UTC, frobware commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	namespace, err := o.nsLister.Get(newRoute.Namespace)
Ahh, are we just confirming the namespace actually exists?

2021-07-27 16:55 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	namespace, err := o.nsLister.Get(newRoute.Namespace)
And nsLister has rights and is setup to access to it.

2021-07-27 17:14 UTC, frobware commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +			synced = append(synced, fmt.Sprintf("%s", n))
> As discussed, will change to 30 seconds.

I really don't know whether this is too much. OTOH, we have customers with 10,000 routes and I don't know how long that will take to sync on a loaded cluster. Given that it will be a one-time affair, I'd rather be a little more conservative vis-a-vis it always fails because 10 seconds was never going to be enough. Would be interested in some feedback here from @sttts @sanchezl.

2021-07-27 19:09 UTC, sanchezl requested changes

2021-07-27 19:09 UTC, sanchezl commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +		oldObject := a.GetOldObject()
Nit: consider using type assertion here to simplify the code below.
```suggestion
		oldObject := a.GetOldObject().(*routeapi.Route)
```

2021-07-27 20:07 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	}
removed, thanks

2021-07-27 20:07 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +		newHSTS, wants = newAnnotations[hstsAnnotation]
removed, thanks

2021-07-27 20:07 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +		if oldObject != nil {
fixed, thanks

2021-07-27 20:07 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +		oldObject := a.GetOldObject()
done, thanks

2021-07-27 20:09 UTC, candita commented
@sanchezl I rebased the commits per your request.

2021-07-27 20:31 UTC, sttts commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +		o.cachesSynced = true
this races

2021-07-27 20:38 UTC, sttts commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +		o.cachesSynced = true
needs locking or an atomic datatype

2021-07-27 21:55 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +		o.cachesSynced = true
Discussed with @sanchezl - removing the boolean, and now checking every time.

2021-07-28 00:50 UTC, candita commented
/test e2e-aws-upgrade

2021-07-28 02:16 UTC, sanchezl approved these changes
/lgtm
/retest

2021-07-28 04:25 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +			synced = append(synced, fmt.Sprintf("%s", n))
After a discussion with @sanchezl , and new feedback from @sttts , we decided to do this every time, and keep it 30 seconds.  30 seconds is a worst case scenario.  If needed, I can call a meeting with all of us together to hash it out.

2021-07-28 13:45 UTC, frobware commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +		o.cachesSynced = true
We could do the following:

```diff
diff --git a/pkg/route/apiserver/admission/requiredrouteannotations/admission.go b/pkg/route/apiserver/admission/requiredrouteannotations/admission.go
index f6b2f9279..268ab3fb0 100644
--- a/pkg/route/apiserver/admission/requiredrouteannotations/admission.go
+++ b/pkg/route/apiserver/admission/requiredrouteannotations/admission.go
@@ -9,6 +9,7 @@ import (
 	"regexp"
 	"strconv"
 	"strings"
+	"sync"
 	"time"
 
 	corev1 "k8s.io/api/core/v1"
@@ -50,7 +51,7 @@ type requiredRouteAnnotations struct {
 	routeLister   routev1listers.RouteLister
 	nsLister      corev1listers.NamespaceLister
 	ingressLister configv1listers.IngressLister
-	cachesSynced  bool
+	cachesSynced  cacheSync
 	cachesToSync  []cache.InformerSynced
 }
 
@@ -62,6 +63,24 @@ var _ = openshiftapiserveradmission.WantsOpenShiftRouteInformers(&requiredRouteA
 
 var maxAgeRegExp = regexp.MustCompile(`max-age=(\d+)`)
 
+type cacheSync struct {
+	readMu    sync.RWMutex
+	writeMu   sync.RWMutex
+	hasSynced bool
+}
+
+func (cs *cacheSync) HasSycned() bool {
+	cs.readMu.Lock()
+	defer cs.readMu.Unlock()
+	return cs.hasSynced
+}
+
+func (cs *cacheSync) SetSynced() {
+	cs.writeMu.Lock()
+	cs.hasSynced = true
+	cs.writeMu.Unlock()
+}
+
 // Validate ensures that routes specify required annotations, and returns nil if valid.
 // The admission handler ensures this is only called for Create/Update operations.
 func (o *requiredRouteAnnotations) Validate(ctx context.Context, a admission.Attributes, _ admission.ObjectInterfaces) (err error) {
@@ -90,11 +109,11 @@ func (o *requiredRouteAnnotations) Validate(ctx context.Context, a admission.Att
 	}
 
 	// Wait up to 30 seconds for all caches to sync.  This is needed only once.
-	if !o.cachesSynced {
-		if synced := o.waitForSyncedStore(ctx); !synced {
+	if !o.cachesSynced.HasSycned() {
+		if !o.waitForSyncedStore(ctx) {
 			return admission.NewForbidden(a, errors.New(pluginName+": caches not synchronized"))
 		}
-		o.cachesSynced = true
+		o.cachesSynced.SetSynced()
 	}
 
 	ingress, err := o.ingressLister.Get("cluster")
```

or more discretely with locking on the read and write access. I tried to encapsulate here to avoid any mistakes.

2021-07-28 13:47 UTC, frobware commented
@candita, @sttts mentioned to me that the we only have 30s for admission calls to complete so let's go for 20s on the sync. Sorry for the churn.

2021-07-28 14:35 UTC, frobware commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +		o.cachesSynced = true
fixing my typo;

```
func (cs *cacheSync) HasSynced() bool {
```

2021-07-28 14:58 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +		o.cachesSynced = true
I made the funcs private and changed a few other minor things.

2021-07-28 15:19 UTC, frobware commented
/lgtm

2021-07-28 15:26 UTC, sttts commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	cacheSyncLock cacheSync
```suggestion
        <empty line>
        isSyncedLock sync.RWMutex
	isSynced bool
```

2021-07-28 15:26 UTC, sttts commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	cacheSyncLock cacheSync
And delete the data type above

2021-07-28 15:28 UTC, sttts commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	}
```suggestion
        isSyncedLock.RLock()
        isSynced = o.isSynced
        isSyncedLock.RUnlock()
        if !isSynched {
		if !o.waitForSyncedStore(ctx) {
			return admission.NewForbidden(a, errors.New(pluginName+": caches not synchronized"))
		}
		isSyncedLock.Lock()
		o.isSynced = true
		isSyncedLock.Unlock()
	}
```

2021-07-28 15:51 UTC, sttts commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +}
```suggestion
func (o *requiredRouteAnnotations) waitForSyncedStore(ctx context.Context) bool {
	        isSyncedLock.RLock()
	        defer isSyncedLock.RLock()
	        if o.isSynced {
	           return nil
	        }
	        
	syncCtx, cancelFn := context.WithTimeout(ctx, timeToWaitForCacheSync)
	defer cancelFn()
	err := cache.WaitForCacheSync(syncCtx.Done(), o.cachesToSync...)
	if err != nil {
	  return err
	 }
	 
	 o.isSyncedLock.Lock()
	 defer o.isSyncedLock.Unlock()
	 o.isSynced = true
	 
	 return err
}
```

2021-07-28 16:18 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +}
I made a similar change, ptal and let me know if you approve by approving. :)

2021-07-28 17:09 UTC, frobware commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	syncCtx, cancelFn := context.WithTimeout(ctx, timeToWaitForCacheSync)
Don't know whether we're just endlessly bike shedding now, particularly if this is temporary and we're gravitating to a more general solution, but creating the context should move insider the if below. Is there any value in creating this each and every call?

2021-07-28 17:16 UTC, frobware commented
/lgtm

2021-07-28 17:19 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	syncCtx, cancelFn := context.WithTimeout(ctx, timeToWaitForCacheSync)
I will take this as a followup, per our discussion.

2021-07-28 19:25 UTC, sttts commented
/retest

2021-07-28 19:26 UTC, sttts commented
/approve

2021-07-28 19:37 UTC, candita commented on pkg/route/apiserver/admission/requiredrouteannotations/admission.go
> +	cacheSyncLock cacheSync
per our chat, this is a moot point

2021-07-28 21:58 UTC, merged