Bug 1971332: revert incorrect ssh scp fix
openshift/openshift-apiserver pull request #238
Opened 2021-07-22 16:07 UTC by gabemontero

we were just wrong with https://github.com/openshift/openshift-apiserver/pull/147

/assign @adambkaplan 

note with the redhat outage tests will fail, even unit (as there is an attempt to access registry.access.redhat.com in one of the tests)

2021-07-22 16:36 UTC, adambkaplan requested changes
Would like to see a test to verify we are OK with SCP style URLs.

2021-07-22 16:36 UTC, adambkaplan commented on pkg/build/apis/build/validation/validation_test.go
> +func TestBuildValidationWithSSHSCPStyledURL(t *testing.T) {
I don't see a test that verifies `git@github.com:sclorg/nodejs-ex` - can you please add one?

2021-07-22 17:03 UTC, gabemontero commented on pkg/build/apis/build/validation/validation_test.go
> +func TestBuildValidationWithSSHSCPStyledURL(t *testing.T) {
added / pushed @adambkaplan

2021-07-22 17:38 UTC, adambkaplan approved these changes
/lgtm

2021-07-23 00:24 UTC, merged

2021-08-11 13:15 UTC, gabemontero commented
/cherrypick release-4.8