Bug 2004203: no longer abort ICT induced builds because of spec last triggered image ID
openshift/openshift-apiserver pull request #246
Opened 2021-09-14 20:36 UTC by gabemontero

https://github.com/openshift/openshift-controller-manager/pull/201 is the more critical of the changes but I thought these changes were still useful for posterity

/assign @adambkaplan 
/assign @alicerum

2021-09-14 21:21 UTC, gabemontero commented
/retest

2021-09-14 23:44 UTC, gabemontero commented
e2e-aws-builds, e2e-aws, e2e-cmd were non sig-builds fails

/retest

2021-09-15 17:49 UTC, adambkaplan requested changes

2021-09-15 17:49 UTC, adambkaplan commented on pkg/build/apiserver/buildgenerator/generator.go
> +	if triggeredBy != nil && (responseTrigger != nil && responseTrigger.LastTriggeredImageID == triggeredBy.Name) {
Why are we dropping the check on the "requestTrigger"?

2021-09-15 17:49 UTC, adambkaplan commented on pkg/build/apiserver/buildgenerator/generator_test.go
> +		oldBC              bool
This is not sufficiently descriptive. I would use a name that indicates we are updating the spec:

```suggestion
		lastTriggeredIDInSpec   bool
```

2021-09-15 17:49 UTC, adambkaplan commented on pkg/build/apiserver/buildgenerator/generator_test.go
> +			oldBC:              true,
```suggestion
			lastTriggeredIDInSpec:              true,
```

2021-09-15 17:49 UTC, adambkaplan commented on pkg/build/apiserver/buildgenerator/generator_test.go
> +		if !tc.oldBC {
```suggestion
		// In 4.9 LastTriggeredImageID is no longer populated in spec. However BuildConfigs from clusters prior to
		// 4.9 may have this field populated.
		if !tc.lastTriggeredIDInSpec {
```

2021-09-15 17:49 UTC, adambkaplan commented on pkg/build/apiserver/buildgenerator/generator_test.go
> +					// Verify that the trigger got updated
```suggestion
					// Verify that the trigger in spec is empty
```

2021-09-15 17:49 UTC, adambkaplan commented on pkg/build/apiserver/buildgenerator/generator_test.go
>  		statusTriggerIndex int // index of trigger in status that will be updated with the imagev1 id, if -1, no update expected
There is a TODO comment above here - please update it.

2021-09-15 19:33 UTC, gabemontero commented on pkg/build/apiserver/buildgenerator/generator.go
> +	if triggeredBy != nil && (responseTrigger != nil && responseTrigger.LastTriggeredImageID == triggeredBy.Name) {
I tried to convey that in the comment below

What got us in the mess in CI included the requestTrigger check flagging things here .... long term, IMO we only want status checks resulting in returning errors on the api server side

But as I tried to convey in the comment below, and the PR description, the meets min for fixing this is *ONLY* https://github.com/openshift/openshift-controller-manager/pull/201 and this change is *NOT* required

But again, I think we should be minimizing the use of the spec field anywhere we can.

We just cannot avoid it in OCM.

Hopefully that clarifies my intent / viewpoint.

WDYT wrt how we proceed here?

2021-09-15 21:31 UTC, gabemontero commented
updates for specific changes pushed @adambkaplan .... we just need to finalize on your "why remove" question and my explanation / answer

2021-09-21 17:37 UTC, gabemontero commented on pkg/build/apiserver/buildgenerator/generator.go
> +	if triggeredBy != nil && (responseTrigger != nil && responseTrigger.LastTriggeredImageID == triggeredBy.Name) {
Thinking through this is certainly warranted as part of review @adambkaplan 

My logic is that:
- once https://github.com/openshift/openshift-controller-manager/pull/201 merges, and with it still inspecting the spec, it will know not to trigger
- wrt ICTs, the ICT controllers in the OCM are the only "clients" that will be posting to this API server EP

Hence, I believe the answer to your question is "no"

Now, if there are flaws in that logic I am missing, then absolutely, we punt on this PR, and continue forever to check both, like we are on the OCM side.

And to reiterate, without https://github.com/openshift/openshift-controller-manager/pull/201, this code as it currently is lead to the repeated triggering churn..  If we had this change in place beforehand, the churn would not have occurred.

But we still need the OCM change to handle the case where a trigger is in fact needed.

2021-09-21 19:02 UTC, adambkaplan commented
/hold

Based on the conversation in https://github.com/openshift/openshift-apiserver/pull/246#discussion_r713270699, this shouldn't merge until https://github.com/openshift/openshift-controller-manager/pull/201 lands.

2021-09-21 19:03 UTC, adambkaplan commented on pkg/build/apiserver/buildgenerator/generator.go
> +	if triggeredBy != nil && (responseTrigger != nil && responseTrigger.LastTriggeredImageID == triggeredBy.Name) {
This makes more sense in light of the OCM pull request. I've place a hold so that the controller manager changes land first.

2021-09-21 19:04 UTC, adambkaplan approved these changes
/lgtm

2021-09-21 19:11 UTC, gabemontero commented on pkg/build/apiserver/buildgenerator/generator.go
> +	if triggeredBy != nil && (responseTrigger != nil && responseTrigger.LastTriggeredImageID == triggeredBy.Name) {
cool / sounds good

2021-09-21 23:16 UTC, gabemontero commented
/hold cancel

2021-09-21 23:17 UTC, merged

2021-09-22 12:51 UTC, gabemontero commented
/cherrypick release-4.9