Bump 1.26 proof
openshift/openshift-apiserver pull request #354
Opened 2023-02-23 20:31 UTC by dinhxuanvu

2023-02-23 21:21 UTC, sanchezl requested changes

2023-02-23 21:21 UTC, sanchezl commented on go.mod
>  	k8s.io/kubernetes => k8s.io/kubernetes v1.25.2
```suggestion
	k8s.io/kubernetes => k8s.io/kubernetes v1.26.1
```

2023-02-23 21:21 UTC, sanchezl commented on go.mod
> +	k8s.io/csi-translation-lib => k8s.io/csi-translation-lib v0.26.1
```suggestion
	k8s.io/csi-translation-lib => k8s.io/csi-translation-lib v0.26.1
	k8s.io/dynamic-resource-allocation => k8s.io/dynamic-resource-allocation v0.26.1
	k8s.io/kms => k8s.io/kms v0.26.1
```

2023-02-28 13:45 UTC, sanchezl requested changes

2023-02-28 13:45 UTC, sanchezl commented on pkg/apps/apis/apps/validation/validation.go
> +	errs = append(errs, validation.ValidateResourceRequirements(&strategy.Resources, nil, fldPath.Child("resources"), kapivalidation.PodValidationOptions{})...)
You can extract the podClaimNames from the `pod.ResourceNames`.

2023-02-28 13:55 UTC, tkashem reviewed
looks good to me, have one question

2023-02-28 13:55 UTC, tkashem commented on pkg/cmd/openshift-apiserver/openshiftapiserver/restoptionsgetter.go
> -	if len(etcdOptions.EncryptionProviderConfigFilepath) != 0 {
we don't need this block any longer?

2023-02-28 14:11 UTC, deads2k commented on pkg/cmd/openshift-apiserver/openshiftapiserver/restoptionsgetter.go
> -	if len(etcdOptions.EncryptionProviderConfigFilepath) != 0 {
> we don't need this block any longer?

Is there an e2e test that ensures our sensitive resources are encrypted when encryption is enabled?  Perhaps turning encryption on in techpreview?

2023-02-28 15:59 UTC, dgrisonnet commented on pkg/cmd/openshift-apiserver/openshiftapiserver/restoptionsgetter.go
> -	if len(etcdOptions.EncryptionProviderConfigFilepath) != 0 {
we have a bunch of e2e tests in the operator: 
- https://github.com/openshift/cluster-openshift-apiserver-operator/blob/master/test/e2e/operator_test.go#L88-L103
- https://github.com/openshift/cluster-openshift-apiserver-operator/tree/master/test/e2e-encryption
- https://github.com/openshift/cluster-openshift-apiserver-operator/tree/master/test/e2e-encryption-rotation

2023-02-28 15:59 UTC, dgrisonnet commented on pkg/cmd/openshift-apiserver/openshiftapiserver/restoptionsgetter.go
> -	if len(etcdOptions.EncryptionProviderConfigFilepath) != 0 {
with regards to this change, I have little confidence it will not break anything since we are not calling `etcdOptions.Complete()`, which is the new way to create Transformers from the encryption config: https://github.com/kubernetes/kubernetes/blob/6f68a13696edb778c21c749d14136c8d26a96493/staging/src/k8s.io/apiserver/pkg/server/options/etcd.go#L218

2023-02-28 16:16 UTC, dinhxuanvu commented on pkg/apps/apis/apps/validation/validation.go
> +	errs = append(errs, validation.ValidateResourceRequirements(&strategy.Resources, nil, fldPath.Child("resources"), kapivalidation.PodValidationOptions{})...)
Fixed. Please double-check. Thanks.

2023-02-28 16:30 UTC, dinhxuanvu commented on pkg/apps/apis/apps/validation/validation.go
> +	podClaimNames := sets.NewString()
@sanchezl Please double check. Thanks.

2023-02-28 16:31 UTC, dinhxuanvu commented on pkg/cmd/openshift-apiserver/openshiftapiserver/restoptionsgetter.go
> +	serverConfig := server.NewConfig(legacyscheme.Codecs)
@dgrisonnet @tkashem What do you think?

2023-02-28 16:38 UTC, dgrisonnet commented on pkg/cmd/openshift-apiserver/openshiftapiserver/restoptionsgetter.go
> -	if len(etcdOptions.EncryptionProviderConfigFilepath) != 0 {
I would suggest refactoring this function to leverage the following configuration mechanism:
```go
if err := etcdOptions.Complete(config.GenericConfig.StorageObjectCountTracker, config.GenericConfig.DrainedNotify()); err != nil {
  return nil, err
}
if err := etcdOptions.ApplyWithStorageFactoryTo(storageFactory, config.GenericConfig); err != nil }
  return nil, err
}
```
I will work on a git diff if it can help you

2023-02-28 16:42 UTC, dgrisonnet commented on pkg/cmd/openshift-apiserver/openshiftapiserver/restoptionsgetter.go
> +	serverConfig := server.NewConfig(legacyscheme.Codecs)
I think we should also leverage https://github.com/kubernetes/kubernetes/blob/6f68a13696edb778c21c749d14136c8d26a96493/staging/src/k8s.io/apiserver/pkg/server/options/etcd.go#L301

2023-02-28 16:57 UTC, dinhxuanvu commented on pkg/cmd/openshift-apiserver/openshiftapiserver/restoptionsgetter.go
> +	serverConfig := server.NewConfig(legacyscheme.Codecs)
Done

2023-02-28 17:11 UTC, dgrisonnet commented on pkg/cmd/openshift-apiserver/openshiftapiserver/restoptionsgetter.go
> -	if len(etcdOptions.EncryptionProviderConfigFilepath) != 0 {
```diff
index 4cee4a520..42a31ab01 100644
--- a/pkg/cmd/openshift-apiserver/openshiftapiserver/config.go
+++ b/pkg/cmd/openshift-apiserver/openshiftapiserver/config.go
@@ -47,11 +47,6 @@ func NewOpenshiftAPIConfig(config *openshiftcontrolplanev1.OpenShiftAPIServerCon
 
        openshiftVersion := version.Get()
 
-       restOptsGetter, err := NewRESTOptionsGetter(config.APIServerArguments, config.StorageConfig)
-       if err != nil {
-               return nil, err
-       }
-
        genericConfig := genericapiserver.NewRecommendedConfig(legacyscheme.Codecs)
        // Current default values
        //Serializer:                   codecs,
@@ -96,7 +91,6 @@ func NewOpenshiftAPIConfig(config *openshiftcontrolplanev1.OpenShiftAPIServerCon
        genericConfig.BuildHandlerChainFunc = OpenshiftHandlerChain
        genericConfig.RequestInfoResolver = apiserverconfig.OpenshiftRequestInfoResolver()
        genericConfig.OpenAPIConfig = configprocessing.DefaultOpenAPIConfig()
-       genericConfig.RESTOptionsGetter = restOptsGetter
        // previously overwritten.  I don't know why
        genericConfig.RequestTimeout = time.Duration(60) * time.Second
        genericConfig.MinRequestTimeout = int(config.ServingInfo.RequestTimeoutSeconds)
@@ -104,6 +98,18 @@ func NewOpenshiftAPIConfig(config *openshiftcontrolplanev1.OpenShiftAPIServerCon
        genericConfig.MaxMutatingRequestsInFlight = int(config.ServingInfo.MaxRequestsInFlight / 2)
        genericConfig.LongRunningFunc = apiserverconfig.IsLongRunningRequest
 
+       etcdOptions, err := ToEtcdOptions(config.APIServerArguments, config.StorageConfig)
+       if err != nil {
+               return nil, err
+       }
+       if err := etcdOptions.Complete(genericConfig.Config.StorageObjectCountTracker, genericConfig.Config.DrainedNotify()); err != nil {
+               return nil, err
+       }
+       storageFactory := NewStorageFactory(etcdOptions)
+       if err := etcdOptions.ApplyWithStorageFactoryTo(storageFactory, &genericConfig.Config); err != nil {
+               return nil, err
+       }
+
        // It is not worse than it was before. This code deserves refactoring.
        // Instead of having a dedicated configuration file, we should pass flags directly.
        // Until then it seems okay to have the following construct.
diff --git a/pkg/cmd/openshift-apiserver/openshiftapiserver/restoptionsgetter.go b/pkg/cmd/openshift-apiserver/openshiftapiserver/restoptionsgetter.go
index da0aba43b..9b7b81dd5 100644
--- a/pkg/cmd/openshift-apiserver/openshiftapiserver/restoptionsgetter.go
+++ b/pkg/cmd/openshift-apiserver/openshiftapiserver/restoptionsgetter.go
@@ -4,9 +4,7 @@ import (
        "strconv"
 
        "k8s.io/apimachinery/pkg/runtime/schema"
-       genericregistry "k8s.io/apiserver/pkg/registry/generic"
        "k8s.io/apiserver/pkg/server/options"
-       "k8s.io/apiserver/pkg/server/options/encryptionconfig"
        apiserverstorage "k8s.io/apiserver/pkg/server/storage"
        serverstorage "k8s.io/apiserver/pkg/server/storage"
        "k8s.io/kubernetes/pkg/api/legacyscheme"
@@ -15,8 +13,7 @@ import (
        "github.com/openshift/openshift-apiserver/pkg/cmd/openshift-apiserver/openshiftapiserver/configprocessing"
 )
 
-// NewConfigGetter returns a restoptions.Getter implemented using information from the provided master config.
-func NewRESTOptionsGetter(startingFlags map[string][]string, storageConfig configv1.EtcdStorageConfig) (genericregistry.RESTOptionsGetter, error) {
+func ToEtcdOptions(startingFlags map[string][]string, storageConfig configv1.EtcdStorageConfig) (*options.EtcdOptions, error) {
        var err error
        targetRAMMB := 0
        if targetRamString := startingFlags["target-ram-mb"]; len(targetRamString) == 1 {
@@ -26,13 +23,15 @@ func NewRESTOptionsGetter(startingFlags map[string][]string, storageConfig confi
                }
        }
 
-       etcdOptions, err := configprocessing.GetEtcdOptions(
+       return configprocessing.GetEtcdOptions(
                startingFlags,
                storageConfig,
                newHeuristicWatchCacheSizes(targetRAMMB),
        )
+}
 
-       storageFactory := apiserverstorage.NewDefaultStorageFactory(
+func NewStorageFactory(etcdOptions *options.EtcdOptions) serverstorage.StorageFactory {
+       return apiserverstorage.NewDefaultStorageFactory(
                etcdOptions.StorageConfig,
                etcdOptions.DefaultStorageMediaType,
                legacyscheme.Codecs,
@@ -40,22 +39,6 @@ func NewRESTOptionsGetter(startingFlags map[string][]string, storageConfig confi
                &serverstorage.ResourceConfig{},
                specialDefaultResourcePrefixes,
        )
-
-       if len(etcdOptions.EncryptionProviderConfigFilepath) != 0 {
-               transformerOverrides, err := encryptionconfig.GetTransformerOverrides(etcdOptions.EncryptionProviderConfigFilepath)
-               if err != nil {
-                       return nil, err
-               }
-               for groupResource, transformer := range transformerOverrides {
-                       storageFactory.SetTransformer(groupResource, transformer)
-               }
-       }
-
-       restOptionsGetter := &options.StorageFactoryRestOptionsFactory{
-               Options:        *etcdOptions,
-               StorageFactory: storageFactory,
-       }
-       return restOptionsGetter, nil
 }
```

2023-02-28 17:13 UTC, dgrisonnet commented on pkg/cmd/openshift-apiserver/openshiftapiserver/restoptionsgetter.go
> -	if len(etcdOptions.EncryptionProviderConfigFilepath) != 0 {
This is what I would do @dinhxuanvu. Also I would rename the `restoptionsgetter.go` file to `etcd.go`.

2023-02-28 17:46 UTC, sanchezl requested changes

2023-02-28 17:46 UTC, sanchezl commented on pkg/apps/apis/apps/validation/validation.go
> +	podClaimNames := sets.NewString()
```suggestion
		if len(podResourceClaim.Name) > 0 {
			podClaimNames.Insert(podResourceClaim.Name)
		}
```
To mirror how they build this list upstream.

2023-02-28 18:04 UTC, dinhxuanvu commented on pkg/apps/apis/apps/validation/validation.go
> +	podClaimNames := sets.NewString()
Can you link to the upstream code? This diff confuses me. The `Name` field is not an array.

2023-02-28 23:10 UTC, dinhxuanvu commented
/retest

2023-02-28 23:23 UTC, dgrisonnet commented
New encryption changes look good to me :+1: 

@dinhxuanvu could you perhaps check if it works with cluster-bot since we don't have any encryption e2e tests in this repo and in origin?

2023-02-28 23:35 UTC, dinhxuanvu commented
> New encryption changes look good to me 👍
> 
> @dinhxuanvu could you perhaps check if it works with cluster-bot since we don't have any encryption e2e tests in this repo and in origin?

Running it right now.

2023-03-01 01:34 UTC, dinhxuanvu commented
/retest

2023-03-01 14:51 UTC, sanchezl approved these changes

2023-03-01 16:49 UTC, dgrisonnet commented
/lgtm

2023-03-01 16:57 UTC, merged