Adds route API changes to set/delete headers.
openshift/openshift-apiserver pull request #380
Opened 2023-07-01 05:24 UTC by miheer

This commit adds route API changes to set/delete headers.
JIRA tiket - https://issues.redhat.com/browse/NE-982
Enhancement Proposal - openshift/enhancements#1296

2023-07-12 08:04 UTC, miheer commented
/retest

2023-07-12 19:21 UTC, miheer commented
/retest

2023-07-13 07:12 UTC, miheer commented
/retest

2023-08-02 12:42 UTC, dinhxuanvu requested changes

2023-08-02 12:57 UTC, miheer commented on go.mod
> +replace github.com/openshift/library-go => github.com/miheer/library-go v0.0.0-20230801235444-cceb757fc9fb
openshift-apiserver  has route type which needs validations to be done in library-go.

2023-08-02 12:59 UTC, miheer commented on go.mod
> +replace github.com/openshift/library-go => github.com/miheer/library-go v0.0.0-20230801235444-cceb757fc9fb
https://github.com/openshift/library-go/pull/1449

2023-08-02 13:17 UTC, dinhxuanvu commented
@Miciah PTAL

2023-08-02 13:46 UTC, Miciah commented on pkg/route/apis/route/types.go
> +	// +kubebuilder:validation:XValidation:rule="!has(self.tls) || self.tls.termination != 'passthrough' || !has(self.httpHeaders)",message="header actions are not permitted when tls termination is pass
Should this file have `kubebuilder` tags?  I don't see `kubebuilder` tags for existing fields.

2023-08-02 13:48 UTC, Miciah commented on pkg/route/apis/route/types.go
> +	HTTPHeaders *RouteHTTPHeaders `json:"httpHeaders,omitempty" protobuf:"bytes,9,opt,name=httpHeaders"`
Should thi sfile have the json/protobuf tags?  I don't see them for existing fields.

2023-08-02 13:49 UTC, Miciah commented on pkg/route/apis/route/types.go
> +	// httpHeaders defines policy for HTTP headers.
The godoc for existing fields refers to the fields by their Go names (e.g. "HTTPHeaders") rather than by their json names ("httpHeaders").

2023-08-02 13:52 UTC, Miciah commented on pkg/route/apis/route/types.go
> +	// +optional
Should this file have `// +optional` tags?  I don't see them on existing fields.

2023-08-02 13:54 UTC, Miciah commented on pkg/route/apis/route/types.go
> +	// +listMapKey=name
I suspect that `listType` and `listMapKey` should be dropped from this file as well, but I defer to the openshift-apiserver maintainers.

2023-08-02 13:55 UTC, Miciah commented on pkg/route/apis/route/types.go
> +	// + Note: Any change to regex mentioned below must be reflected in the CRD validation of route in https://github.com/openshift/library-go/blob/master/pkg/route/validation/validation.go and vice-ver
I don't know whether this note makes sense in this file.

2023-08-02 13:58 UTC, Miciah commented on pkg/route/apis/route/types.go
> +	// +unionMember
Check with the maintainers whether we should keep the `// +unionDiscriminator` and `// +unionMember` tags in this file.

2023-08-02 14:06 UTC, Miciah commented on go.mod
> +replace github.com/openshift/library-go => github.com/miheer/library-go v0.0.0-20230802095901-97cd89d994c3
I see we have  dependency on https://github.com/openshift/library-go/pull/1449.   Please note this in the PR description and add a hold.

2023-08-02 14:08 UTC, dinhxuanvu commented on go.mod
> +replace github.com/openshift/library-go => github.com/miheer/library-go v0.0.0-20230802095901-97cd89d994c3
Yes, this is something I mentioned in my previous PR. This PR won't be merged until this part is done. I can put a hold here.

2023-08-02 14:08 UTC, dinhxuanvu commented
/hold

2023-08-02 14:09 UTC, Miciah commented
Do the changes in https://github.com/openshift/openshift-apiserver/pull/380/commits/e29be6138a7c963f929567e24aa8e21d5baf85db result from https://github.com/openshift/openshift-apiserver/pull/380/commits/7198a5ab6f8e2092db414275b8a5345568a39e1b or from https://github.com/openshift/openshift-apiserver/pull/380/commits/f373bf01cf3a324e62f9fa34e53481655357f2ad?  It might be better to merge the two related commits.

2023-08-03 04:29 UTC, miheer commented
> Do the changes in [e29be61](https://github.com/openshift/openshift-apiserver/commit/e29be6138a7c963f929567e24aa8e21d5baf85db) result from [7198a5a](https://github.com/openshift/openshift-apiserver/commit/7198a5ab6f8e2092db414275b8a5345568a39e1b) or from [f373bf0](https://github.com/openshift/openshift-apiserver/commit/f373bf01cf3a324e62f9fa34e53481655357f2ad)? It might be better to merge the two related commits.

[e29be61](https://github.com/openshift/openshift-apiserver/commit/e29be6138a7c963f929567e24aa8e21d5baf85db) result from [f373bf0](https://github.com/openshift/openshift-apiserver/commit/f373bf01cf3a324e62f9fa34e53481655357f2ad)

2023-08-03 13:03 UTC, miheer commented on pkg/route/apis/route/types.go
> +	HTTPHeaders *RouteHTTPHeaders `json:"httpHeaders,omitempty" protobuf:"bytes,9,opt,name=httpHeaders"`
we can remove it.

2023-08-03 13:03 UTC, miheer commented on pkg/route/apis/route/types.go
> +	// +kubebuilder:validation:XValidation:rule="!has(self.tls) || self.tls.termination != 'passthrough' || !has(self.httpHeaders)",message="header actions are not permitted when tls termination is pass
we can remove it but I was not sure and wanted guidance from the openshift-apiserver team

2023-08-03 13:11 UTC, miheer commented on pkg/route/apis/route/types.go
> +	// +unionMember
i think we will need to remove if we can't keep kubebuilder tags eg: unionDiscrimimator requires setting a Enum
	// +kubebuilder:validation:Enum:=Set;Delete

2023-08-03 13:19 UTC, miheer commented on pkg/route/apis/route/types.go
> +	// for that API field for more details.
i think it will be better to confirm this from the maintainers

2023-08-03 13:20 UTC, miheer commented on pkg/route/apis/route/types.go
> +	// +optional
for now dropped it but need an answer from the maintainers

2023-08-03 17:12 UTC, dinhxuanvu commented on pkg/route/apis/route/types.go
> +	// for that API field for more details.
I think it is fine to keep them the same between versioned and unversioned for the sake of consistency.

2023-08-03 17:14 UTC, dinhxuanvu commented
@Miciah Thanks for the reviews. If things look good, please give it a lgtm.

2023-08-03 19:44 UTC, Miciah commented
/lgtm

2023-08-03 20:47 UTC, dinhxuanvu commented
/hold cancel

2023-08-03 20:48 UTC, dinhxuanvu reviewed
/lgtm

2023-08-03 20:48 UTC, dinhxuanvu commented
/hold
Hold until the library-go PR is merged.

2023-08-04 09:13 UTC, p0lyn0mial commented on pkg/route/apis/route/types.go
> +type RouteHTTPHeaders struct {
What do you think about adding new unit tests somewhere around [here](https://github.com/openshift/openshift-apiserver/blob/25c6ac408c4f90adbc67440f4bb9542c05c2cdf3/pkg/route/apiserver/registry/route/strategy_test.go#L2-L1)?

2023-08-04 09:14 UTC, p0lyn0mial commented on go.mod
>  	k8s.io/cloud-provider v0.27.2
why not to keep all our dependencies on the same level ? (0.27.4)

2023-08-04 09:33 UTC, miheer commented on go.mod
>  	k8s.io/cloud-provider v0.27.2
I have not touched this file manually.
I used go get command for the latest merge commit of api be the added here which has my api fields I need.
I use go mod edit for replacing library-go with my library-go commit.

2023-08-04 09:50 UTC, miheer commented on pkg/route/apis/route/types.go
> +type RouteHTTPHeaders struct {
All the validations are happening in library-go which has all the unit tests in it.

2023-08-04 09:50 UTC, miheer commented on pkg/route/apis/route/types.go
> +type RouteHTTPHeaders struct {
https://github.com/openshift/library-go/pull/1449

2023-08-04 09:59 UTC, miheer commented on pkg/route/apis/route/types.go
> +type RouteHTTPHeaders struct {
pkg/route/apis/route/validation/  the testing has been moved to library-go

2023-08-04 10:05 UTC, p0lyn0mial commented on go.mod
>  	k8s.io/cloud-provider v0.27.2
I understand, but I still feel that it's worth having kube dependencies on the same level.

2023-08-04 10:06 UTC, p0lyn0mial commented on pkg/route/apis/route/types.go
> +type RouteHTTPHeaders struct {
OK, then we will need a smoke test that will prove that the conversion from the internal type to the external one and vice versa works. We can add such a test somewhere around [here](https://github.com/openshift/openshift-apiserver/blob/01c7eec4b7bf3baeb1eb2a7c36ec23b569f378d1/pkg/route/apis/route/v1/conversion_test.go#L13-L12)

2023-08-04 11:26 UTC, miheer commented
just rebased with master and pushed. no structural changes done. lgtm got removed.

2023-08-04 13:16 UTC, p0lyn0mial commented on pkg/route/apis/route/types.go
> +type RouteHTTPHeaders struct {
I think that we need a test that will create a route with your field set (and perhaps a few other fields) in two versions (external and internal) and then simply convert from external to internal and vice versa via `Scheme.Convert` method. 

Here is an example from kube - https://github.com/kubernetes/kubernetes/blob/4911e9de4a7f47f32cf4cdde7c6add54e1ff7cf8/pkg/apis/apps/v1/conversion_test.go#L83

and here is an example from this repository - https://github.com/openshift/openshift-apiserver/blob/01c7eec4b7bf3baeb1eb2a7c36ec23b569f378d1/pkg/apps/apis/apps/v1/conversion_test.go#L55

Having such a test will ensure that the conversions between different versions are working correctly.

2023-08-05 07:52 UTC, miheer commented on go.mod
>  	k8s.io/cloud-provider v0.27.2
hmm Ok but this change won't be related to my PR right ?

2023-08-05 07:52 UTC, miheer commented on go.mod
>  	k8s.io/cloud-provider v0.27.2
i am OK to make these changes in my PR.

2023-08-05 07:53 UTC, miheer commented on pkg/route/apis/route/types.go
> +type RouteHTTPHeaders struct {
OK. I added some tests. PTAL.

2023-08-05 19:07 UTC, Miciah commented on pkg/route/apis/route/v1/conversion_test.go
>  	"k8s.io/apimachinery/pkg/runtime"
```suggestion
	"testing"

	apiequality "k8s.io/apimachinery/pkg/api/equality"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
```

2023-08-05 19:11 UTC, Miciah commented on pkg/route/apis/route/v1/conversion_test.go
> +func TestRouteSpecConversion(t *testing.T) {
I don't know whether it matters, but following the examples that p0lyn0mial referenced, this test should be named `TestV1RouteSpecConversion`.

2023-08-05 19:14 UTC, Miciah commented on pkg/route/apis/route/v1/conversion_test.go
> +	Install(scheme)
These two statements seem to be unnecessary.  What purpose do they serve?  Can you delete them?

2023-08-05 19:17 UTC, Miciah commented on pkg/route/apis/route/v1/conversion_test.go
> +	var headerNameXFrame string = "X-Frame-Options"
Why are you using `:=` for one variable and `var` for the other?
```suggestion
	serviceName := "TestService"
	serviceWeight := int32(0)
	headerNameXFrame := "X-Frame-Options"
```

2023-08-05 19:18 UTC, Miciah commented on pkg/route/apis/route/v1/conversion_test.go
> +					Actions: v1.RouteHTTPHeaderActions{
Why do you have a blank line here?
```suggestion
				HTTPHeaders: &v1.RouteHTTPHeaders{
					Actions: v1.RouteHTTPHeaderActions{
```

2023-08-05 19:18 UTC, Miciah commented on pkg/route/apis/route/v1/conversion_test.go
> +					Actions: route.RouteHTTPHeaderActions{
```suggestion
				HTTPHeaders: &route.RouteHTTPHeaders{
					Actions: route.RouteHTTPHeaderActions{
```

2023-08-05 19:22 UTC, Miciah commented on pkg/route/apis/route/v1/conversion_test.go
> +			t.Errorf("%q - %q: expected\n\t%#v, got \n\t%#v", k, "from apps to appsv1", tc.versionedRouteSpec1, internal1)
```suggestion
			t.Errorf("%q - %q: expected\n\t%#v, got \n\t%#v", k, "from route to routev1", tc.versionedRouteSpec1, internal1)

2023-08-05 19:23 UTC, Miciah commented on pkg/route/apis/route/v1/conversion_test.go
> +			t.Errorf("%q - %q: unexpected error: %v", k, "from appsv1 to apps", err)
```suggestion
			t.Errorf("%q - %q: unexpected error: %v", k, "from routev1 to route err)

2023-08-05 19:23 UTC, Miciah commented on pkg/route/apis/route/v1/conversion_test.go
> +			t.Errorf("%q- %q: expected\n\t%#v, got \n\t%#v", k, "from appsv1 to apps", tc.unversionedRouteSpec2, internal2)
```suggestion
			t.Errorf("%q- %q: expected\n\t%#v, got \n\t%#v", k, "from routev1 to route", tc.unversionedRouteSpec2, internal2)

2023-08-05 19:24 UTC, Miciah commented on pkg/route/apis/route/v1/conversion_test.go
> +			t.Errorf("%q - %q: unexpected error: %v", k, "from unversioned to versioned", err)
I suppose for consistency with the other errors in this test and with the examples that p0lyn0mial referenced, this should be the following:
```suggestion
			t.Errorf("%q - %q: unexpected error: %v", k, "from route to routev1", err)

2023-08-06 01:12 UTC, miheer commented on pkg/route/apis/route/v1/conversion_test.go
> +			t.Errorf("%q - %q: unexpected error: %v", k, "from unversioned to versioned", err)
Yes made this change

2023-08-06 01:20 UTC, miheer commented on pkg/route/apis/route/v1/conversion_test.go
> +			t.Errorf("%q- %q: expected\n\t%#v, got \n\t%#v", k, "from appsv1 to apps", tc.unversionedRouteSpec2, internal2)
done

2023-08-06 01:20 UTC, miheer commented on pkg/route/apis/route/v1/conversion_test.go
> +			t.Errorf("%q - %q: unexpected error: %v", k, "from appsv1 to apps", err)
done

2023-08-06 01:20 UTC, miheer commented on pkg/route/apis/route/v1/conversion_test.go
> +			t.Errorf("%q - %q: expected\n\t%#v, got \n\t%#v", k, "from apps to appsv1", tc.versionedRouteSpec1, internal1)
done

2023-08-06 01:20 UTC, miheer commented on pkg/route/apis/route/v1/conversion_test.go
> +					Actions: route.RouteHTTPHeaderActions{
done

2023-08-06 01:20 UTC, miheer commented on pkg/route/apis/route/v1/conversion_test.go
> +					Actions: v1.RouteHTTPHeaderActions{
done

2023-08-06 01:21 UTC, miheer commented on pkg/route/apis/route/v1/conversion_test.go
> +	var headerNameXFrame string = "X-Frame-Options"
done

2023-08-06 01:21 UTC, miheer commented on pkg/route/apis/route/v1/conversion_test.go
> +	Install(scheme)
yes. removed.

2023-08-06 01:21 UTC, miheer commented on pkg/route/apis/route/v1/conversion_test.go
> +func TestRouteSpecConversion(t *testing.T) {
ok done

2023-08-06 01:21 UTC, miheer commented on pkg/route/apis/route/v1/conversion_test.go
>  	"k8s.io/apimachinery/pkg/runtime"
done

2023-08-06 02:57 UTC, Miciah commented on pkg/route/apis/route/v1/conversion_test.go
>  	"k8s.io/apimachinery/pkg/runtime"
Almost—you still have an extra blank line between `k8s.io/apimachinery/pkg/api/equality` and`k8s.io/apimachinery/pkg/runtime`:
```go
	apiequality "k8s.io/apimachinery/pkg/api/equality"

	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
```

2023-08-06 02:58 UTC, Miciah commented on pkg/route/apis/route/v1/conversion_test.go
> +func TestRouteSpecConversion(t *testing.T) {
Almost—you have `TestRouteV1SpecConversion`, but the examples that p0lyn0mial have the form `TestV1StatefulSetStatusConversion`, so the I think your test should be named `TestV1RouteSpecConversion`.

2023-08-06 09:15 UTC, miheer commented on pkg/route/apis/route/v1/conversion_test.go
> +func TestRouteSpecConversion(t *testing.T) {
ok done

2023-08-06 09:16 UTC, miheer commented on pkg/route/apis/route/v1/conversion_test.go
>  	"k8s.io/apimachinery/pkg/runtime"
ok done

2023-08-06 17:22 UTC, Miciah commented on pkg/route/apis/route/v1/conversion_test.go
>  	Install(scheme)
Can these two lines be removed now that the package-level declarations and init function do the same?

2023-08-07 00:26 UTC, miheer commented on pkg/route/apis/route/v1/conversion_test.go
>  	Install(scheme)
yes done

2023-08-07 11:54 UTC, p0lyn0mial commented on pkg/route/apis/route/v1/conversion_test.go
> +var Convert = scheme.Convert
please make it private (rename to `convert`) especially that the `conversion_test` is exported as `v1`

2023-08-07 11:55 UTC, p0lyn0mial commented on pkg/route/apis/route/v1/conversion_test.go
> +		unversionedRouteSpec2 *route.RouteSpec
nit: I think we call it `internalRouteSpec2`

2023-08-07 11:58 UTC, p0lyn0mial commented on pkg/route/apis/route/v1/conversion_test.go
> +			versionedRouteSpec1: &v1.RouteSpec{
nit: Considering that most fields are static, we could create a function that returns a static spec, and here, only modify what is needed for each test case. It looks like it also applies to `unversionedRouteSpec2/internalRouteSpec2` and other test cases.

2023-08-07 11:59 UTC, p0lyn0mial commented on pkg/route/apis/route/v1/conversion_test.go
> +			t.Errorf("%q - %q: expected\n\t%#v, got \n\t%#v", k, "from route to routev1", tc.versionedRouteSpec1, internal1)
would it make sense to use `cmp.Diff` for logging a human-readable diff?

2023-08-07 12:01 UTC, p0lyn0mial commented on go.mod
>  	k8s.io/cloud-provider v0.27.2
yes, I think we should do it in this PR. I don't expect any issues. Moving from 0.27.2 to 0.27.4 should be seamless.

2023-08-07 12:03 UTC, p0lyn0mial commented on pkg/route/apis/route/v1/conversion_test.go
> +		},
would it make sense to add a case that doesn't set `HTTPHeaders` field ? Just to make sure we can convert a spec without that field set.

2023-08-07 13:17 UTC, miheer commented on pkg/route/apis/route/v1/conversion_test.go
> +			t.Errorf("%q - %q: expected\n\t%#v, got \n\t%#v", k, "from route to routev1", tc.versionedRouteSpec1, internal1)
I think using apiequality.Semantic.DeepEqual will be a more better option as it specifically for comparing APIs.
Also it used in kubernetes repo you pointed out.

2023-08-07 13:27 UTC, miheer commented on pkg/route/apis/route/v1/conversion_test.go
> +		unversionedRouteSpec2 *route.RouteSpec
done

2023-08-07 13:28 UTC, miheer commented on pkg/route/apis/route/v1/conversion_test.go
> +		},
yes done

2023-08-07 13:49 UTC, p0lyn0mial commented on pkg/route/apis/route/v1/conversion_test.go
> +			t.Errorf("%q - %q: expected\n\t%#v, got \n\t%#v", k, "from route to routev1", tc.versionedRouteSpec1, internal1)
I don't want to get rid of `DeepEqual`. I'd like to use `cmp.Diff` to log the diff between the objects - instead of logging full objects. I was thinking abut something like:

```
if !apiequality.Semantic.DeepEqual(internal1, tc.versionedRouteSpec1) {
    t.Errorf("%q - %q: diff: %v", k, "from route to routev1", cmp.Diff(tc.versionedRouteSpec1, internal1))
}
```

2023-08-07 14:05 UTC, miheer commented on pkg/route/apis/route/v1/conversion_test.go
> +			t.Errorf("%q - %q: expected\n\t%#v, got \n\t%#v", k, "from route to routev1", tc.versionedRouteSpec1, internal1)
sure it will help the developers

2023-08-07 14:18 UTC, miheer commented on pkg/route/apis/route/v1/conversion_test.go
> +		unversionedRouteSpec2 *route.RouteSpec
done

2023-08-07 21:14 UTC, miheer commented
/retitle NE-1143 Adds route API changes to set/delete headers.

2023-08-07 21:20 UTC, dinhxuanvu commented
@miheer Would you mind resolving the comments/feedbacks that you already addressed? That will help clearing up the UI here.

2023-08-07 21:46 UTC, miheer commented
> @miheer Would you mind resolving the comments/feedbacks that you already addressed? That will help clearing up the UI here.

done

2023-08-08 06:01 UTC, miheer commented
Just pushed latest openshift/api merge commit. No structural and logical change.

2023-08-08 07:38 UTC, p0lyn0mial commented
@miheer could you also please address https://github.com/openshift/openshift-apiserver/pull/380/commits/809e0e04e7fd66e5c99637d97fc10667ebb62e7e#r1284186731 ?

2023-08-08 08:11 UTC, miheer commented
> @miheer could you also please address [809e0e0#r1284186731](https://github.com/openshift/openshift-apiserver/commit/809e0e04e7fd66e5c99637d97fc10667ebb62e7e#r1284186731) ?

It is not pointing me to what you want.

2023-08-08 08:12 UTC, miheer commented on go.mod
>  	k8s.io/cloud-provider v0.27.2
ok

2023-08-08 08:17 UTC, miheer commented on go.mod
>  	k8s.io/cloud-provider v0.27.2
do you want to make changes in the replace section as well ?

2023-08-08 08:18 UTC, miheer commented on go.mod
>  	k8s.io/cloud-provider v0.27.2
so replace all k8s.io 0.27.2 to 0.27.4 ?

2023-08-08 08:23 UTC, miheer commented
> @miheer could you also please address [809e0e0#r1284186731](https://github.com/openshift/openshift-apiserver/commit/809e0e04e7fd66e5c99637d97fc10667ebb62e7e#r1284186731) ?

Are you mentioning about this ? https://github.com/openshift/openshift-apiserver/pull/380#discussion_r1285770900

2023-08-08 08:36 UTC, p0lyn0mial commented on go.mod
>  	k8s.io/cloud-provider v0.27.2
yes, all k8s deps to 0.27.4 so that they are on the same level.

2023-08-08 09:44 UTC, miheer commented on go.mod
>  	k8s.io/cloud-provider v0.27.2
https://github.com/openshift/openshift-apiserver/compare/7cfeddaca23edf6150ddedf995272ca1395a0d86..af792ebc141417112f3b0b3281b5f00fb436a4a8 @p0lyn0mial 
done

2023-08-08 10:07 UTC, miheer commented
> @miheer could you also please address [809e0e0#r1284186731](https://github.com/openshift/openshift-apiserver/commit/809e0e04e7fd66e5c99637d97fc10667ebb62e7e#r1284186731) ?

done. PTAL

2023-08-08 10:14 UTC, p0lyn0mial commented
/approve

2023-08-08 10:16 UTC, p0lyn0mial commented
we can merge this PR once the library-go PR is merge and we [update the go.mod](we can merge this PR once the librar-go PR is merge and we update the go.mod file) file. thanks!

2023-08-08 17:40 UTC, Miciah commented
[e2e-aws-ovn-serial failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_openshift-apiserver/380/pull-ci-openshift-openshift-apiserver-master-e2e-aws-ovn-serial/1688848417708576768) because `[sig-arch] events should not repeat pathologically for ns/openshift-machine-config-operator` failed:
```text
{  1 events happened too frequently

event happened 21 times, something is wrong: ns/openshift-machine-config-operator machineconfigpool/master hmsg/2f4f9dd984 - pathological/true reason/AnnotationChange (combined from similar events): Node ip-10-0-89-124.us-east-2.compute.internal now has machineconfiguration.openshift.io/reason=failed to set ControllerConfigResourceVersion annotation on node: unable to update node "&Node{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},Spec:NodeSpec{PodCIDR:,DoNotUseExternalID:,ProviderID:,Unschedulable:false,Taints:[]Taint{},ConfigSource:nil,PodCIDRs:[],},Status:NodeStatus{Capacity:ResourceList{},Allocatable:ResourceList{},Phase:,Conditions:[]NodeCondition{},Addresses:[]NodeAddress{},DaemonEndpoints:NodeDaemonEndpoints{KubeletEndpoint:DaemonEndpoint{Port:0,},},NodeInfo:NodeSystemInfo{MachineID:,SystemUUID:,BootID:,KernelVersion:,OSImage:,ContainerRuntimeVersion:,KubeletVersion:,KubeProxyVersion:,OperatingSystem:,Architecture:,},Images:[]ContainerImage{},VolumesInUse:[],VolumesAttached:[]AttachedVolume{},Config:nil,},}": Patch "https://api-int.ci-op-pzwlznzg-698d5.origin-ci-int-aws.dev.rhcloud.com:6443/api/v1/nodes/ip-10-0-89-124.us-east-2.compute.internal": read tcp 10.0.89.124:36822->10.0.12.163:6443: read: connection reset by peer From: 11:49:11Z To: 11:49:12Z result=reject }
```
It appears that the API was unresponsive.  I found [one similar failure](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-network-operator/1905/pull-ci-openshift-cluster-network-operator-master-e2e-aws-ovn-serial/1687009949999173632) in [search.ci](https://search.ci.openshift.org/?search=ns%2Fopenshift-machine-config-operator+machineconfigpool%2Fmaster+%5B%5E+%5D*+-+pathological%2Ftrue+reason%2FAnnotationChange+.*+unable+to+update+node&maxAge=336h&context=1&type=junit&name=e2e-aws-ovn-serial&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job).  Let's see whether this happens again.  

The job also failed because `[Serial] [sig-auth][Feature:OAuthServer] [RequestHeaders] [IdP] test RequestHeaders IdP` failed:
```text
{  fail [github.com/openshift/origin/test/extended/oauth/requestheaders.go:218]: full response header: HTTP/1.1 403 Forbidden
Content-Length: 192
Audit-Id: f6026f9b-06c5-4b4a-9414-8dc5c681b45a
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/json
Date: Tue, 08 Aug 2023 11:26:35 GMT
Expires: 0
Pragma: no-cache
Referrer-Policy: strict-origin-when-cross-origin
X-Content-Type-Options: nosniff
X-Dns-Prefetch-Control: off
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block

{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"forbidden: User \"system:anonymous\" cannot get path \"/metrics\"","reason":"Forbidden","details":{},"code":403}
```
I filed [OCPBUGS-17477](https://issues.redhat.com/browse/OCPBUGS-17477) for this test failure.

/test e2e-aws-ovn-serial

2023-08-08 22:30 UTC, miheer commented
Hi,

Just pushed the latest library-go changes in openshift-apiserver

2023-08-08 22:32 UTC, dinhxuanvu approved these changes
/lgtm

2023-08-08 22:32 UTC, dinhxuanvu commented
/hold cancel

2023-08-09 12:05 UTC, miheer commented
/retest

2023-08-09 15:58 UTC, miheer commented
/retest

2023-08-09 18:25 UTC, merged